import { AnimalConfig } from '../types';

export const ANIMALS: Record<string, AnimalConfig> = {
  chicken: {
    id: 'chicken',
    name: 'Курочка',
    penBuildingId: 'chicken_coop',
    feedItemId: 'chicken_feed',
    produceItemId: 'egg',
    produceTimeSeconds: 20,
    cost: 10,
    xpGain: 3,
    unlockLevel: 1,
    icon: '🐔',
    color: '#FEF08A',
  },
  cow: {
    id: 'cow',
    name: 'Коровка',
    penBuildingId: 'cow_pasture',
    feedItemId: 'cow_feed',
    produceItemId: 'milk',
    produceTimeSeconds: 45,
    cost: 30,
    xpGain: 6,
    unlockLevel: 2,
    icon: '🐄',
    color: '#475569',
  },
  pig: {
    id: 'pig',
    name: 'Свинка',
    penBuildingId: 'pig_pen',
    feedItemId: 'pig_feed',
    produceItemId: 'bacon',
    produceTimeSeconds: 90,
    cost: 100,
    xpGain: 12,
    unlockLevel: 6,
    icon: '🐖',
    color: '#FDA4AF',
  },
  sheep: {
    id: 'sheep',
    name: 'Овечка',
    penBuildingId: 'sheep_meadow',
    feedItemId: 'sheep_feed',
    produceItemId: 'wool',
    produceTimeSeconds: 150,
    cost: 250,
    xpGain: 18,
    unlockLevel: 10,
    icon: '🐑',
    color: '#F1F5F9',
  },
  goat: {
    id: 'goat',
    name: 'Козочка',
    penBuildingId: 'goat_yard',
    feedItemId: 'goat_feed',
    produceItemId: 'goat_milk',
    produceTimeSeconds: 240,
    cost: 500,
    xpGain: 25,
    unlockLevel: 16,
    icon: '🐐',
    color: '#CBD5E1',
  },
};
