import { BuildingConfig } from '../types';

export const BUILDINGS: Record<string, BuildingConfig> = {
  // SPECIAL & STORAGE
  farmhouse: {
    id: 'farmhouse',
    name: 'Фермерский дом',
    category: 'special',
    cost: 0,
    buildTimeSeconds: 0,
    width: 3,
    depth: 3,
    unlockLevel: 1,
    icon: '🏡',
    description: 'Уютный главный дом фермы.',
  },
  silo: {
    id: 'silo',
    name: 'Силосная башня',
    category: 'storage',
    cost: 0,
    buildTimeSeconds: 0,
    width: 2,
    depth: 2,
    unlockLevel: 1,
    icon: '🗼',
    description: 'Хранилище для всех собранных семян, зерна, овощей и фруктов.',
  },
  barn: {
    id: 'barn',
    name: 'Амбар',
    category: 'storage',
    cost: 0,
    buildTimeSeconds: 0,
    width: 3,
    depth: 3,
    unlockLevel: 1,
    icon: '🏚️',
    description: 'Хранилище для продуктов производства, кормов, инструментов и материалов.',
  },
  order_board: {
    id: 'order_board',
    name: 'Доска заказов',
    category: 'special',
    cost: 0,
    buildTimeSeconds: 0,
    width: 2,
    depth: 1,
    unlockLevel: 1,
    icon: '📋',
    description: 'Здесь жители городка оставляют свои заказы на продукты.',
  },
  roadside_shop: {
    id: 'roadside_shop',
    name: 'Придорожный киоск',
    category: 'special',
    cost: 0,
    buildTimeSeconds: 0,
    width: 2,
    depth: 2,
    unlockLevel: 1,
    icon: '🏪',
    description: 'Продавай излишки урожая и товаров другим фермерам и соседям!',
  },
  fishing_dock: {
    id: 'fishing_dock',
    name: 'Рыбацкий причал',
    category: 'special',
    cost: 500,
    buildTimeSeconds: 30,
    width: 3,
    depth: 2,
    unlockLevel: 10,
    icon: '🎣',
    description: 'Лови свежую рыбу и пополняй коллекцию трофеев!',
  },
  field_plot: {
    id: 'field_plot',
    name: 'Грядка (Грунт)',
    category: 'special',
    cost: 10,
    buildTimeSeconds: 0,
    width: 1,
    depth: 1,
    unlockLevel: 1,
    icon: '🌱',
    description: 'Вспаханная плодородная почва для посева и выращивания растений и овощей.',
  },

  // PRODUCTION BUILDINGS
  feed_mill: {
    id: 'feed_mill',
    name: 'Кормовая мельница',
    category: 'production',
    cost: 20,
    buildTimeSeconds: 5,
    width: 2,
    depth: 2,
    unlockLevel: 1,
    icon: '⚙️',
    description: 'Перемалывает зерно и овощи в питательный корм для животных.',
    maxQueueSlots: 5,
  },
  bakery: {
    id: 'bakery',
    name: 'Пекарня',
    category: 'production',
    cost: 50,
    buildTimeSeconds: 10,
    width: 2,
    depth: 2,
    unlockLevel: 1,
    icon: '🥖',
    description: 'Выпекает ароматный хлеб, печенье, пироги и горячую пиццу.',
    maxQueueSlots: 5,
  },
  dairy: {
    id: 'dairy',
    name: 'Молочный завод',
    category: 'production',
    cost: 150,
    buildTimeSeconds: 20,
    width: 2,
    depth: 2,
    unlockLevel: 2,
    icon: '🥛',
    description: 'Перерабатывает свежее молоко в сливки, масло и сыр.',
    maxQueueSlots: 5,
  },
  sugar_mill: {
    id: 'sugar_mill',
    name: 'Сахарный завод',
    category: 'production',
    cost: 350,
    buildTimeSeconds: 30,
    width: 2,
    depth: 2,
    unlockLevel: 5,
    icon: '🍬',
    description: 'Производит тростниковый сахар, белый сахар и сладкий сироп.',
    maxQueueSlots: 5,
  },
  grill: {
    id: 'grill',
    name: 'Гриль-барбекю',
    category: 'production',
    cost: 500,
    buildTimeSeconds: 40,
    width: 2,
    depth: 2,
    unlockLevel: 5,
    icon: '🥩',
    description: 'Жарит сочные бургеры, блинчики, яичницу и овощи гриль.',
    maxQueueSlots: 5,
  },
  pie_oven: {
    id: 'pie_oven',
    name: 'Печь для пирогов',
    category: 'production',
    cost: 800,
    buildTimeSeconds: 60,
    width: 2,
    depth: 2,
    unlockLevel: 6,
    icon: '🥧',
    description: 'Традиционная печь для выпекания морковных, тыквенных и мясных пирогов.',
    maxQueueSlots: 5,
  },
  juicer: {
    id: 'juicer',
    name: 'Соковыжималка',
    category: 'production',
    cost: 1200,
    buildTimeSeconds: 80,
    width: 2,
    depth: 2,
    unlockLevel: 7,
    icon: '🧃',
    description: 'Выжимает свежие натуральные соки, лимонады и смузи.',
    maxQueueSlots: 5,
  },
  loom: {
    id: 'loom',
    name: 'Ткацкий станок',
    category: 'production',
    cost: 1800,
    buildTimeSeconds: 100,
    width: 2,
    depth: 2,
    unlockLevel: 10,
    icon: '🧵',
    description: 'Прядёт хлопковые ткани и шерстяную пряжу из фермерского сырья.',
    maxQueueSlots: 5,
  },
  confectionery: {
    id: 'confectionery',
    name: 'Кондитерская',
    category: 'production',
    cost: 2400,
    buildTimeSeconds: 120,
    width: 2,
    depth: 2,
    unlockLevel: 11,
    icon: '🍭',
    description: 'Мастерская сладостей: карамель, леденцы, шоколад и ириски.',
    maxQueueSlots: 5,
  },
  ice_cream_maker: {
    id: 'ice_cream_maker',
    name: 'Мороженица',
    category: 'production',
    cost: 3200,
    buildTimeSeconds: 150,
    width: 2,
    depth: 2,
    unlockLevel: 12,
    icon: '🍨',
    description: 'Готовит охлаждающее ванильное, ягодное и шоколадное мороженое.',
    maxQueueSlots: 5,
  },
  sewing_shop: {
    id: 'sewing_shop',
    name: 'Швейная мастерская',
    category: 'production',
    cost: 4000,
    buildTimeSeconds: 180,
    width: 2,
    depth: 2,
    unlockLevel: 12,
    icon: '👗',
    description: 'Шьёт стильную тёплую одежду, рубашки, платья и шапки.',
    maxQueueSlots: 5,
  },
  jam_maker: {
    id: 'jam_maker',
    name: 'Вареньеварня',
    category: 'production',
    cost: 5000,
    buildTimeSeconds: 200,
    width: 2,
    depth: 2,
    unlockLevel: 13,
    icon: '🫙',
    description: 'Варит домашние джемы, конфитюры и повидло из свежих ягод.',
    maxQueueSlots: 5,
  },
  coffee_shop: {
    id: 'coffee_shop',
    name: 'Кофейня',
    category: 'production',
    cost: 6500,
    buildTimeSeconds: 240,
    width: 2,
    depth: 2,
    unlockLevel: 14,
    icon: '☕',
    description: 'Варит ароматный кофе: эспрессо, капучино, мокко и горячий шоколад.',
    maxQueueSlots: 5,
  },

  // ANIMAL PENS
  chicken_coop: {
    id: 'chicken_coop',
    name: 'Курятник',
    category: 'animal_pen',
    cost: 20,
    buildTimeSeconds: 5,
    width: 3,
    depth: 3,
    unlockLevel: 1,
    icon: '🐔',
    description: 'Уютный загон для 6 курочек-несушек.',
    associatedAnimalId: 'chicken',
    maxAnimals: 6,
  },
  cow_pasture: {
    id: 'cow_pasture',
    name: 'Коровий выпас',
    category: 'animal_pen',
    cost: 80,
    buildTimeSeconds: 15,
    width: 3,
    depth: 3,
    unlockLevel: 2,
    icon: '🐄',
    description: 'Огороженный зелёный луг для 6 дойных бурёнок.',
    associatedAnimalId: 'cow',
    maxAnimals: 6,
  },
  pig_pen: {
    id: 'pig_pen',
    name: 'Свинарник',
    category: 'animal_pen',
    cost: 250,
    buildTimeSeconds: 30,
    width: 3,
    depth: 3,
    unlockLevel: 6,
    icon: '🐖',
    description: 'Грязевая ванна и кормушки для 6 свинок.',
    associatedAnimalId: 'pig',
    maxAnimals: 6,
  },
  sheep_meadow: {
    id: 'sheep_meadow',
    name: 'Овечий луг',
    category: 'animal_pen',
    cost: 600,
    buildTimeSeconds: 50,
    width: 3,
    depth: 3,
    unlockLevel: 10,
    icon: '🐑',
    description: 'Пастбище для пушистых овечек.',
    associatedAnimalId: 'sheep',
    maxAnimals: 6,
  },
  goat_yard: {
    id: 'goat_yard',
    name: 'Козий дворик',
    category: 'animal_pen',
    cost: 1500,
    buildTimeSeconds: 80,
    width: 3,
    depth: 3,
    unlockLevel: 16,
    icon: '🐐',
    description: 'Горка и загон для бодрых козочек.',
    associatedAnimalId: 'goat',
    maxAnimals: 6,
  },
};
