import { CropConfig, TreeBushConfig } from '../types';

export const CROPS: Record<string, CropConfig> = {
  wheat: {
    id: 'wheat',
    name: 'Пшеница',
    growTimeSeconds: 12,
    cost: 1,
    harvestYield: 2,
    xpGain: 2,
    unlockLevel: 1,
    icon: '🌾',
    color: '#EAB308',
    description: 'Основа для хлеба, кормов и выпечки. Растёт очень быстро.',
  },
  corn: {
    id: 'corn',
    name: 'Кукуруза',
    growTimeSeconds: 25,
    cost: 3,
    harvestYield: 2,
    xpGain: 4,
    unlockLevel: 2,
    icon: '🌽',
    color: '#FACC15',
    description: 'Сладкая сочная кукуруза для кормов и попкорна.',
  },
  carrot: {
    id: 'carrot',
    name: 'Морковь',
    growTimeSeconds: 45,
    cost: 4,
    harvestYield: 2,
    xpGain: 6,
    unlockLevel: 3,
    icon: '🥕',
    color: '#F97316',
    description: 'Хрустящая морковь, любимое лакомство кроликов и пекарей.',
  },
  soybean: {
    id: 'soybean',
    name: 'Соя',
    growTimeSeconds: 60,
    cost: 5,
    harvestYield: 2,
    xpGain: 8,
    unlockLevel: 4,
    icon: '🌱',
    color: '#84CC16',
    description: 'Питательная соя для кормов коров и свиней.',
  },
  sugarcane: {
    id: 'sugarcane',
    name: 'Сахарный тростник',
    growTimeSeconds: 90,
    cost: 6,
    harvestYield: 2,
    xpGain: 10,
    unlockLevel: 5,
    icon: '🎋',
    color: '#10B981',
    description: 'Сладкие стебли для производства коричневого и белого сахара.',
  },
  potato: {
    id: 'potato',
    name: 'Картофель',
    growTimeSeconds: 120,
    cost: 8,
    harvestYield: 2,
    xpGain: 12,
    unlockLevel: 6,
    icon: '🥔',
    color: '#CA8A04',
    description: 'Сытный картофель для гриля, печи и запеканок.',
  },
  tomato: {
    id: 'tomato',
    name: 'Помидор',
    growTimeSeconds: 150,
    cost: 10,
    harvestYield: 2,
    xpGain: 14,
    unlockLevel: 7,
    icon: '🍅',
    color: '#EF4444',
    description: 'Спелые сочные томаты для соков, пиццы и салатов.',
  },
  strawberry: {
    id: 'strawberry',
    name: 'Клубника',
    growTimeSeconds: 180,
    cost: 12,
    harvestYield: 2,
    xpGain: 16,
    unlockLevel: 8,
    icon: '🍓',
    color: '#F43F5E',
    description: 'Ароматная садовая клубника для варенья и тортов.',
  },
  pumpkin: {
    id: 'pumpkin',
    name: 'Тыква',
    growTimeSeconds: 210,
    cost: 15,
    harvestYield: 2,
    xpGain: 18,
    unlockLevel: 9,
    icon: '🎃',
    color: '#EA580C',
    description: 'Большая оранжевая тыква для пирогов и супов.',
  },
  cotton: {
    id: 'cotton',
    name: 'Хлопок',
    growTimeSeconds: 240,
    cost: 18,
    harvestYield: 2,
    xpGain: 20,
    unlockLevel: 10,
    icon: '☁️',
    color: '#F8FAFC',
    description: 'Мягкий хлопок для прядения ткани и пошива одежды.',
  },
  chili: {
    id: 'chili',
    name: 'Острый перец',
    growTimeSeconds: 270,
    cost: 20,
    harvestYield: 2,
    xpGain: 22,
    unlockLevel: 11,
    icon: '🌶️',
    color: '#DC2626',
    description: 'Жгучий перчик для пикантных блюд и соусов на гриле.',
  },
  rice: {
    id: 'rice',
    name: 'Рис',
    growTimeSeconds: 300,
    cost: 22,
    harvestYield: 2,
    xpGain: 24,
    unlockLevel: 12,
    icon: '🍚',
    color: '#F1F5F9',
    description: 'Нежный рис для азиатских блюд и рисовой лапши.',
  },
  lettuce: {
    id: 'lettuce',
    name: 'Салат',
    growTimeSeconds: 330,
    cost: 25,
    harvestYield: 2,
    xpGain: 26,
    unlockLevel: 13,
    icon: '🥬',
    color: '#22C55E',
    description: 'Свежие хрустящие листья салата для полезных сэндвичей.',
  },
  onion: {
    id: 'onion',
    name: 'Лук',
    growTimeSeconds: 360,
    cost: 28,
    harvestYield: 2,
    xpGain: 28,
    unlockLevel: 14,
    icon: '🧅',
    color: '#D97706',
    description: 'Золотистый репчатый лук для рагу и пирогов.',
  },
  garlic: {
    id: 'garlic',
    name: 'Чеснок',
    growTimeSeconds: 390,
    cost: 30,
    harvestYield: 2,
    xpGain: 30,
    unlockLevel: 15,
    icon: '🧄',
    color: '#E2E8F0',
    description: 'Ароматный чеснок с грядки для изысканных соусов.',
  },
  sunflower: {
    id: 'sunflower',
    name: 'Подсолнух',
    growTimeSeconds: 420,
    cost: 32,
    harvestYield: 2,
    xpGain: 32,
    unlockLevel: 16,
    icon: '🌻',
    color: '#EAB308',
    description: 'Солнечный цветок для получения масла и красивых букетов.',
  },
  cabbage: {
    id: 'cabbage',
    name: 'Капуста',
    growTimeSeconds: 450,
    cost: 35,
    harvestYield: 2,
    xpGain: 34,
    unlockLevel: 17,
    icon: '🥦',
    color: '#16A34A',
    description: 'Крепкий кочан свежей капусты для деревенских супов.',
  },
  grape: {
    id: 'grape',
    name: 'Виноград',
    growTimeSeconds: 500,
    cost: 40,
    harvestYield: 2,
    xpGain: 38,
    unlockLevel: 18,
    icon: '🍇',
    color: '#9333EA',
    description: 'Сладкие фиолетовые грозди для изысканных соков и десертов.',
  },
  apple: {
    id: 'apple',
    name: 'Яблоко (Полевое)',
    growTimeSeconds: 540,
    cost: 45,
    harvestYield: 2,
    xpGain: 42,
    unlockLevel: 19,
    icon: '🍏',
    color: '#84CC16',
    description: 'Хрустящие зеленые яблочки для яблочных пирогов.',
  },
  cherry: {
    id: 'cherry',
    name: 'Вишня (Садовая)',
    growTimeSeconds: 600,
    cost: 50,
    harvestYield: 2,
    xpGain: 46,
    unlockLevel: 20,
    icon: '🍒',
    color: '#BE123C',
    description: 'Спелая садовая вишня для варенья и сладкой выпечки.',
  },
};

export const TREES_BUSHES: Record<string, TreeBushConfig> = {
  apple_tree: {
    id: 'apple_tree',
    name: 'Яблоня',
    isTree: true,
    produceItemId: 'apple_fruit',
    growTimeSeconds: 480,
    cost: 160,
    maxHarvests: 4,
    harvestYield: 3,
    xpGain: 25,
    unlockLevel: 8,
    icon: '🍎',
    color: '#EF4444',
  },
  cherry_tree: {
    id: 'cherry_tree',
    name: 'Вишнёвое дерево',
    isTree: true,
    produceItemId: 'cherry_fruit',
    growTimeSeconds: 540,
    cost: 220,
    maxHarvests: 4,
    harvestYield: 3,
    xpGain: 30,
    unlockLevel: 11,
    icon: '🍒',
    color: '#991B1B',
  },
  cacao_tree: {
    id: 'cacao_tree',
    name: 'Какао-дерево',
    isTree: true,
    produceItemId: 'cacao_fruit',
    growTimeSeconds: 660,
    cost: 320,
    maxHarvests: 4,
    harvestYield: 3,
    xpGain: 38,
    unlockLevel: 16,
    icon: '🍫',
    color: '#78350F',
  },
  lemon_tree: {
    id: 'lemon_tree',
    name: 'Лимонное дерево',
    isTree: true,
    produceItemId: 'lemon_fruit',
    growTimeSeconds: 600,
    cost: 280,
    maxHarvests: 4,
    harvestYield: 3,
    xpGain: 35,
    unlockLevel: 13,
    icon: '🍋',
    color: '#FDE047',
  },
  orange_tree: {
    id: 'orange_tree',
    name: 'Апельсиновое дерево',
    isTree: true,
    produceItemId: 'orange_fruit',
    growTimeSeconds: 620,
    cost: 300,
    maxHarvests: 4,
    harvestYield: 3,
    xpGain: 36,
    unlockLevel: 15,
    icon: '🍊',
    color: '#FB923C',
  },
  peach_tree: {
    id: 'peach_tree',
    name: 'Персиковое дерево',
    isTree: true,
    produceItemId: 'peach_fruit',
    growTimeSeconds: 700,
    cost: 360,
    maxHarvests: 4,
    harvestYield: 3,
    xpGain: 40,
    unlockLevel: 18,
    icon: '🍑',
    color: '#FDA4AF',
  },
  raspberry_bush: {
    id: 'raspberry_bush',
    name: 'Куст малины',
    isTree: false,
    produceItemId: 'raspberry_fruit',
    growTimeSeconds: 360,
    cost: 140,
    maxHarvests: 4,
    harvestYield: 3,
    xpGain: 20,
    unlockLevel: 9,
    icon: '🫐',
    color: '#E11D48',
  },
  blackberry_bush: {
    id: 'blackberry_bush',
    name: 'Куст ежевики',
    isTree: false,
    produceItemId: 'blackberry_fruit',
    growTimeSeconds: 420,
    cost: 190,
    maxHarvests: 4,
    harvestYield: 3,
    xpGain: 24,
    unlockLevel: 12,
    icon: '🍇',
    color: '#312E81',
  },
  coffee_bush: {
    id: 'coffee_bush',
    name: 'Кофейный куст',
    isTree: false,
    produceItemId: 'coffee_bean',
    growTimeSeconds: 480,
    cost: 250,
    maxHarvests: 4,
    harvestYield: 3,
    xpGain: 28,
    unlockLevel: 14,
    icon: '☕',
    color: '#451A03',
  },
  blueberry_bush: {
    id: 'blueberry_bush',
    name: 'Куст черники',
    isTree: false,
    produceItemId: 'blueberry_fruit',
    growTimeSeconds: 520,
    cost: 270,
    maxHarvests: 4,
    harvestYield: 3,
    xpGain: 32,
    unlockLevel: 17,
    icon: '🫐',
    color: '#1E40AF',
  },
};
