import { DecorationConfig } from '../types';

export const DECORATIONS: Record<string, DecorationConfig> = {
  // === FENCES ===
  wood_fence: {
    id: 'wood_fence',
    name: 'Деревянный забор',
    category: 'fence',
    cost: 15,
    width: 1,
    depth: 1,
    unlockLevel: 1,
    icon: '🪵',
    color: '#B45309',
  },
  white_fence: {
    id: 'white_fence',
    name: 'Белый штакетник',
    category: 'fence',
    cost: 25,
    width: 1,
    depth: 1,
    unlockLevel: 2,
    icon: '🤍',
    color: '#F8FAFC',
  },
  stone_wall: {
    id: 'stone_wall',
    name: 'Каменная ограда',
    category: 'fence',
    cost: 40,
    width: 1,
    depth: 1,
    unlockLevel: 4,
    icon: '🧱',
    color: '#64748B',
  },
  hedge_fence: {
    id: 'hedge_fence',
    name: 'Живая изгородь',
    category: 'fence',
    cost: 35,
    width: 1,
    depth: 1,
    unlockLevel: 3,
    icon: '🌳',
    color: '#15803D',
  },
  iron_fence: {
    id: 'iron_fence',
    name: 'Кованый забор',
    category: 'fence',
    cost: 60,
    width: 1,
    depth: 1,
    unlockLevel: 7,
    icon: '🛡️',
    color: '#334155',
  },
  candyland_fence: {
    id: 'candyland_fence',
    name: 'Карамельный заборчик',
    category: 'fence',
    cost: 80,
    width: 1,
    depth: 1,
    unlockLevel: 11,
    icon: '🍭',
    color: '#F43F5E',
  },
  bamboo_fence: {
    id: 'bamboo_fence',
    name: 'Бамбуковая изгородь',
    category: 'fence',
    cost: 50,
    width: 1,
    depth: 1,
    unlockLevel: 9,
    icon: '🎋',
    color: '#65A30D',
  },
  golden_fence: {
    id: 'golden_fence',
    name: 'Золотая ограда',
    category: 'fence',
    cost: 200,
    gemsCost: 2,
    width: 1,
    depth: 1,
    unlockLevel: 15,
    icon: '✨',
    color: '#FACC15',
  },

  // === PATHS ===
  dirt_path: {
    id: 'dirt_path',
    name: 'Грунтовая тропинка',
    category: 'path',
    cost: 10,
    width: 1,
    depth: 1,
    unlockLevel: 1,
    icon: '🟤',
    color: '#A16207',
  },
  stone_path: {
    id: 'stone_path',
    name: 'Каменная дорожка',
    category: 'path',
    cost: 20,
    width: 1,
    depth: 1,
    unlockLevel: 2,
    icon: '⚪',
    color: '#94A3B8',
  },
  brick_path: {
    id: 'brick_path',
    name: 'Кирпичная мостовая',
    category: 'path',
    cost: 30,
    width: 1,
    depth: 1,
    unlockLevel: 5,
    icon: '🧱',
    color: '#C2410C',
  },
  cobblestone_path: {
    id: 'cobblestone_path',
    name: 'Булыжная мостовая',
    category: 'path',
    cost: 35,
    width: 1,
    depth: 1,
    unlockLevel: 8,
    icon: '🪨',
    color: '#475569',
  },
  wooden_plank_path: {
    id: 'wooden_plank_path',
    name: 'Деревянный настил',
    category: 'path',
    cost: 25,
    width: 1,
    depth: 1,
    unlockLevel: 4,
    icon: '🪵',
    color: '#854D0E',
  },
  flower_border_path: {
    id: 'flower_border_path',
    name: 'Цветочная аллея',
    category: 'path',
    cost: 45,
    width: 1,
    depth: 1,
    unlockLevel: 6,
    icon: '🌸',
    color: '#EC4899',
  },
  mosaic_path: {
    id: 'mosaic_path',
    name: 'Мозаичная плитка',
    category: 'path',
    cost: 60,
    width: 1,
    depth: 1,
    unlockLevel: 12,
    icon: '💠',
    color: '#06B6D4',
  },
  sand_path: {
    id: 'sand_path',
    name: 'Песчаная дорожка',
    category: 'path',
    cost: 15,
    width: 1,
    depth: 1,
    unlockLevel: 3,
    icon: '🏖️',
    color: '#FDE047',
  },

  // === FLOWERS & PLANTERS ===
  red_tulips: {
    id: 'red_tulips',
    name: 'Красные тюльпаны',
    category: 'flower',
    cost: 20,
    width: 1,
    depth: 1,
    unlockLevel: 1,
    icon: '🌷',
    color: '#EF4444',
  },
  yellow_daisies: {
    id: 'yellow_daisies',
    name: 'Желтые ромашки',
    category: 'flower',
    cost: 20,
    width: 1,
    depth: 1,
    unlockLevel: 2,
    icon: '🌼',
    color: '#FACC15',
  },
  blue_hydrangeas: {
    id: 'blue_hydrangeas',
    name: 'Синие гортензии',
    category: 'flower',
    cost: 30,
    width: 1,
    depth: 1,
    unlockLevel: 3,
    icon: '💐',
    color: '#3B82F6',
  },
  pink_roses: {
    id: 'pink_roses',
    name: 'Розовые розы',
    category: 'flower',
    cost: 40,
    width: 1,
    depth: 1,
    unlockLevel: 4,
    icon: '🌹',
    color: '#F43F5E',
  },
  sunflower_planter: {
    id: 'sunflower_planter',
    name: 'Клумба подсолнухов',
    category: 'flower',
    cost: 60,
    width: 1,
    depth: 1,
    unlockLevel: 7,
    icon: '🌻',
    color: '#EAB308',
  },
  flower_barrel: {
    id: 'flower_barrel',
    name: 'Бочка с цветами',
    category: 'flower',
    cost: 45,
    width: 1,
    depth: 1,
    unlockLevel: 3,
    icon: '🛢️',
    color: '#A16207',
  },
  lavender_patch: {
    id: 'lavender_patch',
    name: 'Лавандовая полянка',
    category: 'flower',
    cost: 50,
    width: 1,
    depth: 1,
    unlockLevel: 8,
    icon: '🪻',
    color: '#A855F7',
  },
  rose_bush: {
    id: 'rose_bush',
    name: 'Куст алых роз',
    category: 'flower',
    cost: 70,
    width: 1,
    depth: 1,
    unlockLevel: 8,
    icon: '🌹',
    color: '#E11D48',
  },

  // === LIGHTING ===
  stone_lamp: {
    id: 'stone_lamp',
    name: 'Каменный фонарик',
    category: 'lighting',
    cost: 50,
    width: 1,
    depth: 1,
    unlockLevel: 3,
    icon: '🏮',
    color: '#F59E0B',
  },
  street_lantern: {
    id: 'street_lantern',
    name: 'Уличный фонарь',
    category: 'lighting',
    cost: 80,
    width: 1,
    depth: 1,
    unlockLevel: 5,
    icon: '💡',
    color: '#FDE047',
  },
  pier_lantern: {
    id: 'pier_lantern',
    name: 'Морской фонарь',
    category: 'lighting',
    cost: 100,
    width: 1,
    depth: 1,
    unlockLevel: 10,
    icon: '🏮',
    color: '#0284C7',
  },
  street_lamp_gold: {
    id: 'street_lamp_gold',
    name: 'Золотой фонарный столб',
    category: 'lighting',
    cost: 180,
    gemsCost: 1,
    width: 1,
    depth: 1,
    unlockLevel: 14,
    icon: '✨',
    color: '#EAB308',
  },
  fairy_lights_pole: {
    id: 'fairy_lights_pole',
    name: 'Столбик с гирляндой',
    category: 'lighting',
    cost: 120,
    width: 1,
    depth: 1,
    unlockLevel: 9,
    icon: '✨',
    color: '#EC4899',
  },

  // === WATER & FOUNTAINS ===
  small_fountain: {
    id: 'small_fountain',
    name: 'Малый фонтанчик',
    category: 'water',
    cost: 150,
    width: 2,
    depth: 2,
    unlockLevel: 5,
    icon: '⛲',
    color: '#38BDF8',
  },
  grand_fountain: {
    id: 'grand_fountain',
    name: 'Парадный фонтан',
    category: 'water',
    cost: 450,
    gemsCost: 3,
    width: 3,
    depth: 3,
    unlockLevel: 15,
    icon: '⛲',
    color: '#0284C7',
  },
  wishing_well: {
    id: 'wishing_well',
    name: 'Колодец желаний',
    category: 'water',
    cost: 220,
    width: 2,
    depth: 2,
    unlockLevel: 13,
    icon: '🪣',
    color: '#64748B',
  },
  stone_well: {
    id: 'stone_well',
    name: 'Каменный колодец',
    category: 'water',
    cost: 120,
    width: 1,
    depth: 1,
    unlockLevel: 10,
    icon: '🧱',
    color: '#475569',
  },
  koi_pond: {
    id: 'koi_pond',
    name: 'Прудик с карпами',
    category: 'water',
    cost: 320,
    width: 2,
    depth: 2,
    unlockLevel: 11,
    icon: '🐟',
    color: '#0EA5E9',
  },
  crystal_fountain: {
    id: 'crystal_fountain',
    name: 'Хрустальный каскад',
    category: 'water',
    cost: 800,
    gemsCost: 5,
    width: 3,
    depth: 3,
    unlockLevel: 20,
    icon: '💎',
    color: '#67E8F9',
  },

  // === FURNITURE & REST ===
  wooden_bench: {
    id: 'wooden_bench',
    name: 'Деревянная скамейка',
    category: 'furniture',
    cost: 40,
    width: 1,
    depth: 1,
    unlockLevel: 4,
    icon: '🪑',
    color: '#A16207',
  },
  marble_bench: {
    id: 'marble_bench',
    name: 'Мраморная скамья',
    category: 'furniture',
    cost: 90,
    width: 1,
    depth: 1,
    unlockLevel: 12,
    icon: '🪑',
    color: '#E2E8F0',
  },
  picnic_table: {
    id: 'picnic_table',
    name: 'Стол для пикника',
    category: 'furniture',
    cost: 110,
    width: 2,
    depth: 2,
    unlockLevel: 6,
    icon: '🧺',
    color: '#854D0E',
  },
  cafe_table: {
    id: 'cafe_table',
    name: 'Кафейный столик с зонтиком',
    category: 'furniture',
    cost: 160,
    width: 2,
    depth: 2,
    unlockLevel: 14,
    icon: '⛱️',
    color: '#E11D48',
  },
  gazebo: {
    id: 'gazebo',
    name: 'Садовая беседка',
    category: 'furniture',
    cost: 500,
    gemsCost: 4,
    width: 3,
    depth: 3,
    unlockLevel: 17,
    icon: '🏛️',
    color: '#F8FAFC',
  },
  hammock: {
    id: 'hammock',
    name: 'Гамак между берёзами',
    category: 'furniture',
    cost: 200,
    width: 2,
    depth: 1,
    unlockLevel: 9,
    icon: '🏕️',
    color: '#22C55E',
  },

  // === STATUES & SCULPTURES ===
  garden_gnome: {
    id: 'garden_gnome',
    name: 'Садовый гномик',
    category: 'statue',
    cost: 75,
    width: 1,
    depth: 1,
    unlockLevel: 7,
    icon: '🧙‍♂️',
    color: '#DC2626',
  },
  pumpkin_scarecrow: {
    id: 'pumpkin_scarecrow',
    name: 'Пугало Тыквоголовый',
    category: 'statue',
    cost: 95,
    width: 1,
    depth: 1,
    unlockLevel: 9,
    icon: '🎃',
    color: '#EA580C',
  },
  candy_statue: {
    id: 'candy_statue',
    name: 'Карамельный мишка',
    category: 'statue',
    cost: 220,
    width: 1,
    depth: 1,
    unlockLevel: 11,
    icon: '🧸',
    color: '#FB7185',
  },
  ice_cream_cone_sculpture: {
    id: 'ice_cream_cone_sculpture',
    name: 'Скульптура Мороженое',
    category: 'statue',
    cost: 260,
    width: 1,
    depth: 1,
    unlockLevel: 12,
    icon: '🍦',
    color: '#FDE047',
  },
  topiary_peacock: {
    id: 'topiary_peacock',
    name: 'Куст-Павлин',
    category: 'statue',
    cost: 340,
    width: 2,
    depth: 2,
    unlockLevel: 17,
    icon: '🦚',
    color: '#15803D',
  },
  golden_harvester_statue: {
    id: 'golden_harvester_statue',
    name: 'Золотая статуя Жнеца',
    category: 'statue',
    cost: 1200,
    gemsCost: 8,
    width: 2,
    depth: 2,
    unlockLevel: 18,
    icon: '👑',
    color: '#EAB308',
  },
  golden_windmill: {
    id: 'golden_windmill',
    name: 'Декоративная ветряная мельница',
    category: 'statue',
    cost: 1500,
    gemsCost: 10,
    width: 2,
    depth: 2,
    unlockLevel: 19,
    icon: '🌬️',
    color: '#F59E0B',
  },

  // === RURAL & ACCENTS ===
  hay_bale: {
    id: 'hay_bale',
    name: 'Тюк сена',
    category: 'furniture',
    cost: 15,
    width: 1,
    depth: 1,
    unlockLevel: 1,
    icon: '🌾',
    color: '#EAB308',
  },
  wooden_cart: {
    id: 'wooden_cart',
    name: 'Телега с тыквами',
    category: 'furniture',
    cost: 85,
    width: 2,
    depth: 1,
    unlockLevel: 9,
    icon: '🛒',
    color: '#B45309',
  },
  apple_crate: {
    id: 'apple_crate',
    name: 'Ящик со спелыми яблоками',
    category: 'furniture',
    cost: 35,
    width: 1,
    depth: 1,
    unlockLevel: 6,
    icon: '🍎',
    color: '#EF4444',
  },
  hedge_arch: {
    id: 'hedge_arch',
    name: 'Зелёная арка',
    category: 'furniture',
    cost: 180,
    width: 2,
    depth: 1,
    unlockLevel: 15,
    icon: '⛩️',
    color: '#16A34A',
  },
  grape_arbor: {
    id: 'grape_arbor',
    name: 'Виноградная пергола',
    category: 'furniture',
    cost: 290,
    width: 2,
    depth: 2,
    unlockLevel: 18,
    icon: '🍇',
    color: '#7E22CE',
  },
  sunflower_arch: {
    id: 'sunflower_arch',
    name: 'Солнечная цветочная арка',
    category: 'furniture',
    cost: 230,
    width: 2,
    depth: 1,
    unlockLevel: 16,
    icon: '🌻',
    color: '#EAB308',
  },
  royal_garden_arch: {
    id: 'royal_garden_arch',
    name: 'Королевская триумфальная арка',
    category: 'furniture',
    cost: 950,
    gemsCost: 6,
    width: 3,
    depth: 1,
    unlockLevel: 20,
    icon: '🏛️',
    color: '#FACC15',
  },
};
