import { ObstacleConfig } from '../types';

export const OBSTACLES: Record<string, ObstacleConfig> = {
  small_tree: {
    id: 'small_tree',
    name: 'Сухое дерево',
    toolRequired: 'axe',
    width: 1,
    depth: 1,
    xpReward: 10,
    dropItemId: 'wood_panel',
    color: '#78350F',
  },
  big_tree: {
    id: 'big_tree',
    name: 'Вековой дуб',
    toolRequired: 'saw',
    width: 2,
    depth: 2,
    xpReward: 25,
    dropItemId: 'plank',
    color: '#451A03',
  },
  tree_stump: {
    id: 'tree_stump',
    name: 'Старый пень',
    toolRequired: 'axe',
    width: 1,
    depth: 1,
    xpReward: 8,
    dropItemId: 'nail',
    color: '#92400E',
  },
  small_rock: {
    id: 'small_rock',
    name: 'Камень',
    toolRequired: 'pickaxe',
    width: 1,
    depth: 1,
    xpReward: 12,
    dropItemId: 'screw',
    color: '#64748B',
  },
  large_boulder: {
    id: 'large_boulder',
    name: 'Скала валун',
    toolRequired: 'dynamite',
    width: 2,
    depth: 2,
    xpReward: 35,
    dropItemId: 'bolt',
    color: '#334155',
  },
  mud_puddle: {
    id: 'mud_puddle',
    name: 'Грязная лужа',
    toolRequired: 'shovel',
    width: 1,
    depth: 1,
    xpReward: 10,
    dropItemId: 'duct_tape',
    color: '#713F12',
  },
  wild_bush: {
    id: 'wild_bush',
    name: 'Колючий кустарник',
    toolRequired: 'axe',
    width: 1,
    depth: 1,
    xpReward: 6,
    dropItemId: 'nail',
    color: '#166534',
  },
};
