import { GameItem } from '../types';

export const PRODUCTS: Record<string, GameItem> = {
  // === CROPS (SILO STORAGE) ===
  wheat: {
    id: 'wheat',
    name: 'Пшеница',
    category: 'crop',
    storage: 'silo',
    basePrice: 3,
    xpGain: 1,
    icon: '🌾',
    description: 'Золотая пшеница для мельницы и пекарни.',
    unlockLevel: 1,
    color: '#EAB308',
  },
  corn: {
    id: 'corn',
    name: 'Кукуруза',
    category: 'crop',
    storage: 'silo',
    basePrice: 7,
    xpGain: 2,
    icon: '🌽',
    description: 'Сладкие зерна кукурузы.',
    unlockLevel: 2,
    color: '#FACC15',
  },
  carrot: {
    id: 'carrot',
    name: 'Морковь',
    category: 'crop',
    storage: 'silo',
    basePrice: 10,
    xpGain: 3,
    icon: '🥕',
    description: 'Хрустящая оранжевая морковь.',
    unlockLevel: 3,
    color: '#F97316',
  },
  soybean: {
    id: 'soybean',
    name: 'Соя',
    category: 'crop',
    storage: 'silo',
    basePrice: 14,
    xpGain: 4,
    icon: '🌱',
    description: 'Питательные соевые бобы.',
    unlockLevel: 4,
    color: '#84CC16',
  },
  sugarcane: {
    id: 'sugarcane',
    name: 'Сахарный тростник',
    category: 'crop',
    storage: 'silo',
    basePrice: 18,
    xpGain: 5,
    icon: '🎋',
    description: 'Стебли тростника для сахара.',
    unlockLevel: 5,
    color: '#10B981',
  },
  potato: {
    id: 'potato',
    name: 'Картофель',
    category: 'crop',
    storage: 'silo',
    basePrice: 22,
    xpGain: 6,
    icon: '🥔',
    description: 'Крупные клубни картофеля.',
    unlockLevel: 6,
    color: '#CA8A04',
  },
  tomato: {
    id: 'tomato',
    name: 'Помидор',
    category: 'crop',
    storage: 'silo',
    basePrice: 26,
    xpGain: 7,
    icon: '🍅',
    description: 'Спелые сочные томаты.',
    unlockLevel: 7,
    color: '#EF4444',
  },
  strawberry: {
    id: 'strawberry',
    name: 'Клубника',
    category: 'crop',
    storage: 'silo',
    basePrice: 32,
    xpGain: 8,
    icon: '🍓',
    description: 'Сладкая полевая клубника.',
    unlockLevel: 8,
    color: '#F43F5E',
  },
  pumpkin: {
    id: 'pumpkin',
    name: 'Тыква',
    category: 'crop',
    storage: 'silo',
    basePrice: 38,
    xpGain: 9,
    icon: '🎃',
    description: 'Большая спелая тыква.',
    unlockLevel: 9,
    color: '#EA580C',
  },
  cotton: {
    id: 'cotton',
    name: 'Хлопок',
    category: 'crop',
    storage: 'silo',
    basePrice: 42,
    xpGain: 10,
    icon: '☁️',
    description: 'Пушистые коробочки хлопка.',
    unlockLevel: 10,
    color: '#F8FAFC',
  },
  chili: {
    id: 'chili',
    name: 'Острый перец',
    category: 'crop',
    storage: 'silo',
    basePrice: 48,
    xpGain: 11,
    icon: '🌶️',
    description: 'Красный жгучий перчик.',
    unlockLevel: 11,
    color: '#DC2626',
  },
  rice: {
    id: 'rice',
    name: 'Рис',
    category: 'crop',
    storage: 'silo',
    basePrice: 52,
    xpGain: 12,
    icon: '🍚',
    description: 'Белый отборный рис.',
    unlockLevel: 12,
    color: '#F1F5F9',
  },
  lettuce: {
    id: 'lettuce',
    name: 'Салат',
    category: 'crop',
    storage: 'silo',
    basePrice: 56,
    xpGain: 13,
    icon: '🥬',
    description: 'Свежие листья салата.',
    unlockLevel: 13,
    color: '#22C55E',
  },
  onion: {
    id: 'onion',
    name: 'Лук',
    category: 'crop',
    storage: 'silo',
    basePrice: 60,
    xpGain: 14,
    icon: '🧅',
    description: 'Золотистый репчатый лук.',
    unlockLevel: 14,
    color: '#D97706',
  },
  garlic: {
    id: 'garlic',
    name: 'Чеснок',
    category: 'crop',
    storage: 'silo',
    basePrice: 65,
    xpGain: 15,
    icon: '🧄',
    description: 'Пряные дольки чеснока.',
    unlockLevel: 15,
    color: '#E2E8F0',
  },
  sunflower: {
    id: 'sunflower',
    name: 'Подсолнух',
    category: 'crop',
    storage: 'silo',
    basePrice: 70,
    xpGain: 16,
    icon: '🌻',
    description: 'Яркие семена подсолнуха.',
    unlockLevel: 16,
    color: '#EAB308',
  },
  cabbage: {
    id: 'cabbage',
    name: 'Капуста',
    category: 'crop',
    storage: 'silo',
    basePrice: 75,
    xpGain: 17,
    icon: '🥦',
    description: 'Плотный кочан капусты.',
    unlockLevel: 17,
    color: '#16A34A',
  },
  grape: {
    id: 'grape',
    name: 'Виноград',
    category: 'crop',
    storage: 'silo',
    basePrice: 82,
    xpGain: 19,
    icon: '🍇',
    description: 'Сочные виноградные грозди.',
    unlockLevel: 18,
    color: '#9333EA',
  },
  apple: {
    id: 'apple',
    name: 'Яблоко',
    category: 'crop',
    storage: 'silo',
    basePrice: 90,
    xpGain: 21,
    icon: '🍏',
    description: 'Спелое садовое яблоко.',
    unlockLevel: 19,
    color: '#84CC16',
  },
  cherry: {
    id: 'cherry',
    name: 'Вишня',
    category: 'crop',
    storage: 'silo',
    basePrice: 98,
    xpGain: 23,
    icon: '🍒',
    description: 'Кисло-сладкая сочная вишня.',
    unlockLevel: 20,
    color: '#BE123C',
  },

  // === FRUITS & BERRIES (SILO STORAGE) ===
  apple_fruit: {
    id: 'apple_fruit',
    name: 'Яблоки с дерева',
    category: 'fruit',
    storage: 'silo',
    basePrice: 40,
    xpGain: 10,
    icon: '🍎',
    description: 'Свежесобранные красные яблоки.',
    unlockLevel: 8,
    color: '#EF4444',
  },
  cherry_fruit: {
    id: 'cherry_fruit',
    name: 'Вишня с дерева',
    category: 'fruit',
    storage: 'silo',
    basePrice: 55,
    xpGain: 12,
    icon: '🍒',
    description: 'Ягоды спелой вишни.',
    unlockLevel: 11,
    color: '#991B1B',
  },
  raspberry_fruit: {
    id: 'raspberry_fruit',
    name: 'Малина',
    category: 'fruit',
    storage: 'silo',
    basePrice: 45,
    xpGain: 10,
    icon: '🫐',
    description: 'Сладкая лесная малина.',
    unlockLevel: 9,
    color: '#E11D48',
  },
  blackberry_fruit: {
    id: 'blackberry_fruit',
    name: 'Ежевика',
    category: 'fruit',
    storage: 'silo',
    basePrice: 60,
    xpGain: 14,
    icon: '🍇',
    description: 'Тёмные ягоды ежевики.',
    unlockLevel: 12,
    color: '#312E81',
  },
  lemon_fruit: {
    id: 'lemon_fruit',
    name: 'Лимон',
    category: 'fruit',
    storage: 'silo',
    basePrice: 68,
    xpGain: 15,
    icon: '🍋',
    description: 'Ароматный кислый лимон.',
    unlockLevel: 13,
    color: '#FDE047',
  },
  coffee_bean: {
    id: 'coffee_bean',
    name: 'Кофейные зёрна',
    category: 'fruit',
    storage: 'silo',
    basePrice: 72,
    xpGain: 16,
    icon: '☕',
    description: 'Спелые зёрна кофе.',
    unlockLevel: 14,
    color: '#451A03',
  },
  orange_fruit: {
    id: 'orange_fruit',
    name: 'Апельсин',
    category: 'fruit',
    storage: 'silo',
    basePrice: 76,
    xpGain: 17,
    icon: '🍊',
    description: 'Сладкий сочный апельсин.',
    unlockLevel: 15,
    color: '#FB923C',
  },
  cacao_fruit: {
    id: 'cacao_fruit',
    name: 'Какао-бобы',
    category: 'fruit',
    storage: 'silo',
    basePrice: 85,
    xpGain: 18,
    icon: '🍫',
    description: 'Бобы для шоколада.',
    unlockLevel: 16,
    color: '#78350F',
  },
  blueberry_fruit: {
    id: 'blueberry_fruit',
    name: 'Черника',
    category: 'fruit',
    storage: 'silo',
    basePrice: 90,
    xpGain: 19,
    icon: '🫐',
    description: 'Полезная черника.',
    unlockLevel: 17,
    color: '#1E40AF',
  },
  peach_fruit: {
    id: 'peach_fruit',
    name: 'Персик',
    category: 'fruit',
    storage: 'silo',
    basePrice: 95,
    xpGain: 20,
    icon: '🍑',
    description: 'Бархатистый сладкий персик.',
    unlockLevel: 18,
    color: '#FDA4AF',
  },

  // === ANIMAL PRODUCTS (BARN STORAGE) ===
  egg: {
    id: 'egg',
    name: 'Яйцо',
    category: 'animal_product',
    storage: 'barn',
    basePrice: 18,
    xpGain: 5,
    icon: '🥚',
    description: 'Свежее куриное яйцо.',
    unlockLevel: 1,
    color: '#FEF08A',
  },
  milk: {
    id: 'milk',
    name: 'Молоко',
    category: 'animal_product',
    storage: 'barn',
    basePrice: 32,
    xpGain: 8,
    icon: '🥛',
    description: 'Парное коровье молоко.',
    unlockLevel: 2,
    color: '#F8FAFC',
  },
  bacon: {
    id: 'bacon',
    name: 'Бекон',
    category: 'animal_product',
    storage: 'barn',
    basePrice: 50,
    xpGain: 12,
    icon: '🥓',
    description: 'Аппетитный мясной бекон.',
    unlockLevel: 6,
    color: '#F43F5E',
  },
  wool: {
    id: 'wool',
    name: 'Овечья шерсть',
    category: 'animal_product',
    storage: 'barn',
    basePrice: 65,
    xpGain: 15,
    icon: '🧶',
    description: 'Мягкая стриженая шерсть.',
    unlockLevel: 10,
    color: '#E2E8F0',
  },
  goat_milk: {
    id: 'goat_milk',
    name: 'Козье молоко',
    category: 'animal_product',
    storage: 'barn',
    basePrice: 80,
    xpGain: 18,
    icon: '🫗',
    description: 'Густое и полезное козье молоко.',
    unlockLevel: 16,
    color: '#F1F5F9',
  },

  // === FEEDS (BARN STORAGE) ===
  chicken_feed: {
    id: 'chicken_feed',
    name: 'Куриный корм',
    category: 'feed',
    storage: 'barn',
    basePrice: 7,
    xpGain: 2,
    icon: '🥣',
    description: 'Питательная смесь для курочек.',
    unlockLevel: 1,
    color: '#FDE047',
  },
  cow_feed: {
    id: 'cow_feed',
    name: 'Коровий корм',
    category: 'feed',
    storage: 'barn',
    basePrice: 14,
    xpGain: 4,
    icon: '🌾',
    description: 'Смесь кукурузы и сои для коров.',
    unlockLevel: 2,
    color: '#84CC16',
  },
  pig_feed: {
    id: 'pig_feed',
    name: 'Свиной корм',
    category: 'feed',
    storage: 'barn',
    basePrice: 20,
    xpGain: 6,
    icon: '🥕',
    description: 'Корм из моркови и сои.',
    unlockLevel: 6,
    color: '#FB923C',
  },
  sheep_feed: {
    id: 'sheep_feed',
    name: 'Овечий корм',
    category: 'feed',
    storage: 'barn',
    basePrice: 26,
    xpGain: 8,
    icon: '🌱',
    description: 'Свежая смесь для овечек.',
    unlockLevel: 10,
    color: '#4ADE80',
  },
  goat_feed: {
    id: 'goat_feed',
    name: 'Козий корм',
    category: 'feed',
    storage: 'barn',
    basePrice: 32,
    xpGain: 10,
    icon: '🌾',
    description: 'Отборное зерно для коз.',
    unlockLevel: 16,
    color: '#A3E635',
  },

  // === BAKERY PRODUCTS ===
  bread: {
    id: 'bread',
    name: 'Хлеб',
    category: 'processed',
    storage: 'barn',
    basePrice: 22,
    xpGain: 6,
    icon: '🍞',
    description: 'Ароматная буханка хрустящего хлеба.',
    unlockLevel: 1,
    color: '#D97706',
  },
  corn_bread: {
    id: 'corn_bread',
    name: 'Кукурузный хлеб',
    category: 'processed',
    storage: 'barn',
    basePrice: 48,
    xpGain: 12,
    icon: '🥖',
    description: 'Золотистый хлеб из кукурузной муки.',
    unlockLevel: 3,
    color: '#EAB308',
  },
  cookie: {
    id: 'cookie',
    name: 'Печенье',
    category: 'processed',
    storage: 'barn',
    basePrice: 65,
    xpGain: 16,
    icon: '🍪',
    description: 'Сладкое хрустящее печенье с сахаром.',
    unlockLevel: 5,
    color: '#B45309',
  },
  muffin: {
    id: 'muffin',
    name: 'Маффин с малиной',
    category: 'processed',
    storage: 'barn',
    basePrice: 95,
    xpGain: 22,
    icon: '🧁',
    description: 'Нежный кекс с ягодами.',
    unlockLevel: 9,
    color: '#EC4899',
  },
  pizza: {
    id: 'pizza',
    name: 'Пицца',
    category: 'dish',
    storage: 'barn',
    basePrice: 190,
    xpGain: 45,
    icon: '🍕',
    description: 'Горячая пицца с сыром и томатами.',
    unlockLevel: 12,
    color: '#EF4444',
  },
  spicy_pizza: {
    id: 'spicy_pizza',
    name: 'Острая пицца',
    category: 'dish',
    storage: 'barn',
    basePrice: 240,
    xpGain: 55,
    icon: '🍕',
    description: 'Пицца с острым перцем и беконом.',
    unlockLevel: 14,
    color: '#DC2626',
  },
  bagel: {
    id: 'bagel',
    name: 'Бейгл с кунжутом',
    category: 'processed',
    storage: 'barn',
    basePrice: 110,
    xpGain: 26,
    icon: '🥯',
    description: 'Румяный бублик для завтрака.',
    unlockLevel: 15,
    color: '#D97706',
  },

  // === DAIRY PRODUCTS ===
  cream: {
    id: 'cream',
    name: 'Сливки',
    category: 'processed',
    storage: 'barn',
    basePrice: 50,
    xpGain: 12,
    icon: '🍶',
    description: 'Густые жирные сливки.',
    unlockLevel: 2,
    color: '#FEF9C3',
  },
  butter: {
    id: 'butter',
    name: 'Сливочное масло',
    category: 'processed',
    storage: 'barn',
    basePrice: 85,
    xpGain: 20,
    icon: '🧈',
    description: 'Натуральное домашнее масло.',
    unlockLevel: 4,
    color: '#FACC15',
  },
  cheese: {
    id: 'cheese',
    name: 'Сыр',
    category: 'processed',
    storage: 'barn',
    basePrice: 120,
    xpGain: 28,
    icon: '🧀',
    description: 'Выдержанный сыр с дырочками.',
    unlockLevel: 6,
    color: '#F59E0B',
  },
  goat_cheese: {
    id: 'goat_cheese',
    name: 'Козий сыр',
    category: 'processed',
    storage: 'barn',
    basePrice: 165,
    xpGain: 38,
    icon: '🧀',
    description: 'Нежный деликатесный козий сырок.',
    unlockLevel: 16,
    color: '#FDE68A',
  },
  yogurt: {
    id: 'yogurt',
    name: 'Йогурт',
    category: 'processed',
    storage: 'barn',
    basePrice: 140,
    xpGain: 32,
    icon: '🍧',
    description: 'Натуральный йогурт с ягодами.',
    unlockLevel: 18,
    color: '#F472B6',
  },

  // === SUGAR MILL PRODUCTS ===
  brown_sugar: {
    id: 'brown_sugar',
    name: 'Тростниковый сахар',
    category: 'processed',
    storage: 'barn',
    basePrice: 32,
    xpGain: 8,
    icon: '🟤',
    description: 'Ароматный коричневый сахар.',
    unlockLevel: 5,
    color: '#92400E',
  },
  white_sugar: {
    id: 'white_sugar',
    name: 'Белый сахар',
    category: 'processed',
    storage: 'barn',
    basePrice: 52,
    xpGain: 12,
    icon: '⚪',
    description: 'Рафинированный кристаллический сахар.',
    unlockLevel: 7,
    color: '#F8FAFC',
  },
  syrup: {
    id: 'syrup',
    name: 'Сахарный сироп',
    category: 'processed',
    storage: 'barn',
    basePrice: 88,
    xpGain: 20,
    icon: '🍯',
    description: 'Густой сладкий сироп для десертов.',
    unlockLevel: 11,
    color: '#D97706',
  },

  // === GRILL DISHES ===
  pancake: {
    id: 'pancake',
    name: 'Блинчики с сиропом',
    category: 'dish',
    storage: 'barn',
    basePrice: 110,
    xpGain: 26,
    icon: '🥞',
    description: 'Стопка румяных пышных блинов.',
    unlockLevel: 5,
    color: '#F59E0B',
  },
  bacon_eggs: {
    id: 'bacon_eggs',
    name: 'Яичница с беконом',
    category: 'dish',
    storage: 'barn',
    basePrice: 155,
    xpGain: 35,
    icon: '🍳',
    description: 'Сытный фермерский завтрак.',
    unlockLevel: 7,
    color: '#FB923C',
  },
  hamburger: {
    id: 'hamburger',
    name: 'Бургер с котлетой',
    category: 'dish',
    storage: 'barn',
    basePrice: 180,
    xpGain: 42,
    icon: '🍔',
    description: 'Сочный бургер со свежими овощами.',
    unlockLevel: 10,
    color: '#B45309',
  },
  grilled_fish: {
    id: 'grilled_fish',
    name: 'Рыба на гриле',
    category: 'dish',
    storage: 'barn',
    basePrice: 220,
    xpGain: 50,
    icon: '🐟',
    description: 'Ароматная рыбка со специями.',
    unlockLevel: 13,
    color: '#38BDF8',
  },
  roast_potato: {
    id: 'roast_potato',
    name: 'Печёный картофель',
    category: 'dish',
    storage: 'barn',
    basePrice: 130,
    xpGain: 30,
    icon: '🥔',
    description: 'Картофель с маслом и зеленью.',
    unlockLevel: 8,
    color: '#CA8A04',
  },
  grilled_veggies: {
    id: 'grilled_veggies',
    name: 'Овощи гриль',
    category: 'dish',
    storage: 'barn',
    basePrice: 160,
    xpGain: 36,
    icon: '🥗',
    description: 'Перцы, помидоры и лук с дымком.',
    unlockLevel: 15,
    color: '#10B981',
  },

  // === PIE OVEN PRODUCTS ===
  carrot_pie: {
    id: 'carrot_pie',
    name: 'Морковный пирог',
    category: 'dish',
    storage: 'barn',
    basePrice: 95,
    xpGain: 22,
    icon: '🥧',
    description: 'Пряный нежный морковный пирог.',
    unlockLevel: 6,
    color: '#F97316',
  },
  pumpkin_pie: {
    id: 'pumpkin_pie',
    name: 'Тыквенный пирог',
    category: 'dish',
    storage: 'barn',
    basePrice: 150,
    xpGain: 34,
    icon: '🥧',
    description: 'Традиционный осенний пирог из тыквы.',
    unlockLevel: 9,
    color: '#EA580C',
  },
  bacon_pie: {
    id: 'bacon_pie',
    name: 'Киш с беконом',
    category: 'dish',
    storage: 'barn',
    basePrice: 195,
    xpGain: 44,
    icon: '🥧',
    description: 'Сытный пирог с мясом и яйцами.',
    unlockLevel: 11,
    color: '#E11D48',
  },
  apple_pie: {
    id: 'apple_pie',
    name: 'Яблочный пирог',
    category: 'dish',
    storage: 'barn',
    basePrice: 230,
    xpGain: 52,
    icon: '🥧',
    description: 'Сладкий пирог со свежими яблоками.',
    unlockLevel: 14,
    color: '#84CC16',
  },
  fish_pie: {
    id: 'fish_pie',
    name: 'Рыбный пирог',
    category: 'dish',
    storage: 'barn',
    basePrice: 260,
    xpGain: 60,
    icon: '🥧',
    description: 'Морской деликатес в слоёном тесте.',
    unlockLevel: 17,
    color: '#0284C7',
  },

  // === JUICER PRODUCTS ===
  carrot_juice: {
    id: 'carrot_juice',
    name: 'Морковный сок',
    category: 'processed',
    storage: 'barn',
    basePrice: 60,
    xpGain: 14,
    icon: '🧃',
    description: 'Витаминный свежевыжатый сок.',
    unlockLevel: 7,
    color: '#F97316',
  },
  apple_juice: {
    id: 'apple_juice',
    name: 'Яблочный сок',
    category: 'processed',
    storage: 'barn',
    basePrice: 110,
    xpGain: 25,
    icon: '🧃',
    description: 'Освежающий сок из сладких яблок.',
    unlockLevel: 9,
    color: '#84CC16',
  },
  cherry_juice: {
    id: 'cherry_juice',
    name: 'Вишнёвый сок',
    category: 'processed',
    storage: 'barn',
    basePrice: 145,
    xpGain: 32,
    icon: '🧃',
    description: 'Густой рубиновый напиток.',
    unlockLevel: 12,
    color: '#991B1B',
  },
  tomato_juice: {
    id: 'tomato_juice',
    name: 'Томатный сок',
    category: 'processed',
    storage: 'barn',
    basePrice: 125,
    xpGain: 28,
    icon: '🧃',
    description: 'Насыщенный сок со щепоткой соли.',
    unlockLevel: 10,
    color: '#EF4444',
  },
  lemonade: {
    id: 'lemonade',
    name: 'Лимонад со льдом',
    category: 'processed',
    storage: 'barn',
    basePrice: 170,
    xpGain: 38,
    icon: '🍹',
    description: 'Прохладный напиток с лимоном и сахаром.',
    unlockLevel: 13,
    color: '#FDE047',
  },
  orange_juice: {
    id: 'orange_juice',
    name: 'Апельсиновый фреш',
    category: 'processed',
    storage: 'barn',
    basePrice: 185,
    xpGain: 42,
    icon: '🧃',
    description: 'Цитрусовый заряд бодрости.',
    unlockLevel: 15,
    color: '#FB923C',
  },
  berry_smoothie: {
    id: 'berry_smoothie',
    name: 'Ягодный смузи',
    category: 'processed',
    storage: 'barn',
    basePrice: 220,
    xpGain: 50,
    icon: '🥤',
    description: 'Коктейль из малины, ежевики и молока.',
    unlockLevel: 17,
    color: '#9333EA',
  },

  // === LOOM & SEWING SHOP PRODUCTS ===
  cotton_fabric: {
    id: 'cotton_fabric',
    name: 'Хлопковая ткань',
    category: 'processed',
    storage: 'barn',
    basePrice: 90,
    xpGain: 20,
    icon: '🧵',
    description: 'Прочное белое полотно.',
    unlockLevel: 10,
    color: '#F8FAFC',
  },
  wool_yarn: {
    id: 'wool_yarn',
    name: 'Шерстяная пряжа',
    category: 'processed',
    storage: 'barn',
    basePrice: 120,
    xpGain: 28,
    icon: '🧶',
    description: 'Тёплые мотки мягкой пряжи.',
    unlockLevel: 11,
    color: '#CBD5E1',
  },
  sweater: {
    id: 'sweater',
    name: 'Шерстяной свитер',
    category: 'processed',
    storage: 'barn',
    basePrice: 280,
    xpGain: 62,
    icon: '🧥',
    description: 'Уютный свитер крупной вязки.',
    unlockLevel: 12,
    color: '#64748B',
  },
  cotton_shirt: {
    id: 'cotton_shirt',
    name: 'Хлопковая рубашка',
    category: 'processed',
    storage: 'barn',
    basePrice: 230,
    xpGain: 52,
    icon: '👔',
    description: 'Стильная лёгкая рубашка.',
    unlockLevel: 13,
    color: '#38BDF8',
  },
  warm_beanie: {
    id: 'warm_beanie',
    name: 'Тёплая шапка',
    category: 'processed',
    storage: 'barn',
    basePrice: 180,
    xpGain: 40,
    icon: '🧢',
    description: 'Шерстяная шапочка на осень и зиму.',
    unlockLevel: 14,
    color: '#E11D48',
  },
  dress: {
    id: 'dress',
    name: 'Летнее платье',
    category: 'processed',
    storage: 'barn',
    basePrice: 350,
    xpGain: 78,
    icon: '👗',
    description: 'Изящное платье с хлопковой каймой.',
    unlockLevel: 16,
    color: '#F472B6',
  },

  // === CONFECTIONERY PRODUCTS ===
  caramel: {
    id: 'caramel',
    name: 'Карамель',
    category: 'processed',
    storage: 'barn',
    basePrice: 140,
    xpGain: 32,
    icon: '🍬',
    description: 'Сливочные тягучие конфеты.',
    unlockLevel: 11,
    color: '#D97706',
  },
  chocolate_bar: {
    id: 'chocolate_bar',
    name: 'Плитка шоколада',
    category: 'processed',
    storage: 'barn',
    basePrice: 260,
    xpGain: 58,
    icon: '🍫',
    description: 'Настоящий молочный шоколад из какао.',
    unlockLevel: 16,
    color: '#78350F',
  },
  lollipop: {
    id: 'lollipop',
    name: 'Леденец на палочке',
    category: 'processed',
    storage: 'barn',
    basePrice: 175,
    xpGain: 38,
    icon: '🍭',
    description: 'Фруктовый яркий леденец.',
    unlockLevel: 13,
    color: '#F43F5E',
  },
  toffee: {
    id: 'toffee',
    name: 'Ирис с орехами',
    category: 'processed',
    storage: 'barn',
    basePrice: 210,
    xpGain: 48,
    icon: '🍬',
    description: 'Твёрдые сладкие ириски.',
    unlockLevel: 15,
    color: '#CA8A04',
  },
  cotton_candy: {
    id: 'cotton_candy',
    name: 'Сахарная вата',
    category: 'processed',
    storage: 'barn',
    basePrice: 190,
    xpGain: 42,
    icon: '🍡',
    description: 'Воздушное сладкое облако.',
    unlockLevel: 17,
    color: '#F472B6',
  },

  // === ICE CREAM PRODUCTS ===
  vanilla_icecream: {
    id: 'vanilla_icecream',
    name: 'Ванильное мороженое',
    category: 'processed',
    storage: 'barn',
    basePrice: 160,
    xpGain: 36,
    icon: '🍨',
    description: 'Классический пломбир со сливками.',
    unlockLevel: 12,
    color: '#FEF08A',
  },
  cherry_popsicle: {
    id: 'cherry_popsicle',
    name: 'Вишнёвый эскимо',
    category: 'processed',
    storage: 'barn',
    basePrice: 195,
    xpGain: 44,
    icon: '🍦',
    description: 'Фруктовый лёд из спелой вишни.',
    unlockLevel: 13,
    color: '#BE123C',
  },
  strawberry_icecream: {
    id: 'strawberry_icecream',
    name: 'Клубничное мороженое',
    category: 'processed',
    storage: 'barn',
    basePrice: 230,
    xpGain: 52,
    icon: '🍨',
    description: 'Кремовое мороженое с кусочками клубники.',
    unlockLevel: 15,
    color: '#FB7185',
  },
  chocolate_sundae: {
    id: 'chocolate_sundae',
    name: 'Шоколадный сандай',
    category: 'processed',
    storage: 'barn',
    basePrice: 310,
    xpGain: 70,
    icon: '🍨',
    description: 'Шоколадное мороженое с топпингом.',
    unlockLevel: 17,
    color: '#78350F',
  },

  // === JAM MAKER PRODUCTS ===
  apple_jam: {
    id: 'apple_jam',
    name: 'Яблочное повидло',
    category: 'processed',
    storage: 'barn',
    basePrice: 180,
    xpGain: 40,
    icon: '🫙',
    description: 'Густое янтарное повидло.',
    unlockLevel: 13,
    color: '#EAB308',
  },
  raspberry_jam: {
    id: 'raspberry_jam',
    name: 'Малиновое варенье',
    category: 'processed',
    storage: 'barn',
    basePrice: 215,
    xpGain: 48,
    icon: '🫙',
    description: 'Ароматное домашнее варенье.',
    unlockLevel: 14,
    color: '#E11D48',
  },
  blackberry_jam: {
    id: 'blackberry_jam',
    name: 'Ежевичный джем',
    category: 'processed',
    storage: 'barn',
    basePrice: 245,
    xpGain: 55,
    icon: '🫙',
    description: 'Насыщенный терпкий джем.',
    unlockLevel: 15,
    color: '#4338CA',
  },
  cherry_jam: {
    id: 'cherry_jam',
    name: 'Вишнёвый конфитюр',
    category: 'processed',
    storage: 'barn',
    basePrice: 270,
    xpGain: 60,
    icon: '🫙',
    description: 'Конфитюр с цельными ягодами.',
    unlockLevel: 16,
    color: '#991B1B',
  },
  peach_marmalade: {
    id: 'peach_marmalade',
    name: 'Персиковый мармелад',
    category: 'processed',
    storage: 'barn',
    basePrice: 310,
    xpGain: 68,
    icon: '🫙',
    description: 'Нежный мармелад из спелых персиков.',
    unlockLevel: 19,
    color: '#FB923C',
  },

  // === COFFEE SHOP PRODUCTS ===
  espresso: {
    id: 'espresso',
    name: 'Эспрессо',
    category: 'dish',
    storage: 'barn',
    basePrice: 190,
    xpGain: 42,
    icon: '☕',
    description: 'Крепкий бодрящий чёрный кофе.',
    unlockLevel: 14,
    color: '#451A03',
  },
  cappuccino: {
    id: 'cappuccino',
    name: 'Капучино',
    category: 'dish',
    storage: 'barn',
    basePrice: 250,
    xpGain: 56,
    icon: '☕',
    description: 'Кофе с пышной молочной пенкой.',
    unlockLevel: 15,
    color: '#D97706',
  },
  hot_chocolate: {
    id: 'hot_chocolate',
    name: 'Горячий шоколад',
    category: 'dish',
    storage: 'barn',
    basePrice: 320,
    xpGain: 72,
    icon: '☕',
    description: 'Густой шоколадный напиток со сливками.',
    unlockLevel: 16,
    color: '#78350F',
  },
  iced_latte: {
    id: 'iced_latte',
    name: 'Айс латте',
    category: 'dish',
    storage: 'barn',
    basePrice: 290,
    xpGain: 65,
    icon: '🧋',
    description: 'Освежающий холодный кофе с молоком.',
    unlockLevel: 17,
    color: '#B45309',
  },
  mocha: {
    id: 'mocha',
    name: 'Мокачино',
    category: 'dish',
    storage: 'barn',
    basePrice: 360,
    xpGain: 80,
    icon: '☕',
    description: 'Кофе с какао и взбитыми сливками.',
    unlockLevel: 18,
    color: '#581C87',
  },

  // === FISH SPECIES (BARN STORAGE) ===
  perch: {
    id: 'perch',
    name: 'Речной окунь',
    category: 'fish',
    storage: 'barn',
    basePrice: 65,
    xpGain: 15,
    icon: '🐟',
    description: 'Полосатый обитатель речных заводей.',
    unlockLevel: 10,
    color: '#16A34A',
  },
  trout: {
    id: 'trout',
    name: 'Радужная форель',
    category: 'fish',
    storage: 'barn',
    basePrice: 115,
    xpGain: 28,
    icon: '🐟',
    description: 'Благородная речная рыба с пятнышками.',
    unlockLevel: 11,
    color: '#EC4899',
  },
  carp: {
    id: 'carp',
    name: 'Зеркальный карп',
    category: 'fish',
    storage: 'barn',
    basePrice: 160,
    xpGain: 36,
    icon: '🐟',
    description: 'Крупная сытная рыба из пруда.',
    unlockLevel: 12,
    color: '#CA8A04',
  },
  salmon: {
    id: 'salmon',
    name: 'Дикий лосось',
    category: 'fish',
    storage: 'barn',
    basePrice: 220,
    xpGain: 50,
    icon: '🐟',
    description: 'Ценная промысловая рыба.',
    unlockLevel: 14,
    color: '#FB7185',
  },
  pike: {
    id: 'pike',
    name: 'Щука',
    category: 'fish',
    storage: 'barn',
    basePrice: 280,
    xpGain: 65,
    icon: '🦈',
    description: 'Хищная зубастая речная рыба.',
    unlockLevel: 16,
    color: '#059669',
  },
  golden_tench: {
    id: 'golden_tench',
    name: 'Золотой линь',
    category: 'fish',
    storage: 'barn',
    basePrice: 420,
    xpGain: 95,
    icon: '✨',
    description: 'Редчайшая сияющая рыба-легенда.',
    unlockLevel: 18,
    color: '#EAB308',
  },

  // === TOOLS & OBSTACLE CLEARING (BARN STORAGE) ===
  axe: {
    id: 'axe',
    name: 'Топор лесоруба',
    category: 'tool',
    storage: 'barn',
    basePrice: 40,
    xpGain: 10,
    icon: '🪓',
    description: 'Нужен для рубки сухих деревьев и веток.',
    unlockLevel: 1,
    color: '#94A3B8',
  },
  saw: {
    id: 'saw',
    name: 'Пила',
    category: 'tool',
    storage: 'barn',
    basePrice: 65,
    xpGain: 15,
    icon: '🪚',
    description: 'Спиливает крупные вековые деревья.',
    unlockLevel: 3,
    color: '#64748B',
  },
  dynamite: {
    id: 'dynamite',
    name: 'Динамитная шашка',
    category: 'tool',
    storage: 'barn',
    basePrice: 85,
    xpGain: 20,
    icon: '🧨',
    description: 'Взрывает скальные глыбы и валуны.',
    unlockLevel: 5,
    color: '#EF4444',
  },
  shovel: {
    id: 'shovel',
    name: 'Лопата',
    category: 'tool',
    storage: 'barn',
    basePrice: 55,
    xpGain: 12,
    icon: '⛏️',
    description: 'Убирает грязевые лужи и канавы.',
    unlockLevel: 4,
    color: '#71717A',
  },
  pickaxe: {
    id: 'pickaxe',
    name: 'Кирка',
    category: 'tool',
    storage: 'barn',
    basePrice: 95,
    xpGain: 22,
    icon: '⛏️',
    description: 'Раскалывает камни и рудные залежи.',
    unlockLevel: 7,
    color: '#3B82F6',
  },

  // === EXPANSION & BUILDING UPGRADE MATERIALS (BARN STORAGE) ===
  nail: {
    id: 'nail',
    name: 'Гвозди',
    category: 'material',
    storage: 'barn',
    basePrice: 120,
    xpGain: 25,
    icon: '🔩',
    description: 'Для улучшения вместимости Силоса.',
    unlockLevel: 2,
    color: '#94A3B8',
  },
  screw: {
    id: 'screw',
    name: 'Шурупы',
    category: 'material',
    storage: 'barn',
    basePrice: 120,
    xpGain: 25,
    icon: '🔩',
    description: 'Для улучшения вместимости Силоса.',
    unlockLevel: 2,
    color: '#64748B',
  },
  wood_panel: {
    id: 'wood_panel',
    name: 'Деревянные доски',
    category: 'material',
    storage: 'barn',
    basePrice: 120,
    xpGain: 25,
    icon: '🪵',
    description: 'Для расширения Силоса.',
    unlockLevel: 2,
    color: '#B45309',
  },
  bolt: {
    id: 'bolt',
    name: 'Болты',
    category: 'material',
    storage: 'barn',
    basePrice: 150,
    xpGain: 30,
    icon: '🔩',
    description: 'Для укрепления и расширения Амбара.',
    unlockLevel: 3,
    color: '#475569',
  },
  plank: {
    id: 'plank',
    name: 'Брус',
    category: 'material',
    storage: 'barn',
    basePrice: 150,
    xpGain: 30,
    icon: '🪵',
    description: 'Крепкий брус для Амбара.',
    unlockLevel: 3,
    color: '#92400E',
  },
  duct_tape: {
    id: 'duct_tape',
    name: 'Клейкая лента',
    category: 'material',
    storage: 'barn',
    basePrice: 150,
    xpGain: 30,
    icon: '🩹',
    description: 'Для починки и расширения Амбара.',
    unlockLevel: 3,
    color: '#0284C7',
  },
  land_deed: {
    id: 'land_deed',
    name: 'Купчая на землю',
    category: 'material',
    storage: 'barn',
    basePrice: 250,
    xpGain: 50,
    icon: '📜',
    description: 'Документ для открытия новых участков карты.',
    unlockLevel: 8,
    color: '#FEF08A',
  },
  mallet: {
    id: 'mallet',
    name: 'Деревянный молот',
    category: 'material',
    storage: 'barn',
    basePrice: 250,
    xpGain: 50,
    icon: '🔨',
    description: 'Инструмент для разметки границы фермы.',
    unlockLevel: 8,
    color: '#D97706',
  },
  marker_stake: {
    id: 'marker_stake',
    name: 'Межевой колышек',
    category: 'material',
    storage: 'barn',
    basePrice: 250,
    xpGain: 50,
    icon: '📍',
    description: 'Колышек для отметки новых границ.',
    unlockLevel: 8,
    color: '#EF4444',
  },
};
