import { RecipeConfig } from '../types';

export const RECIPES: Record<string, RecipeConfig> = {
  // === FEED MILL ===
  feed_chicken: {
    id: 'feed_chicken',
    buildingId: 'feed_mill',
    name: 'Куриный корм x3',
    outputItemId: 'chicken_feed',
    outputCount: 3,
    craftTimeSeconds: 5,
    ingredients: [
      { itemId: 'wheat', count: 2 },
      { itemId: 'corn', count: 1 },
    ],
    unlockLevel: 1,
    xpGain: 2,
  },
  feed_cow: {
    id: 'feed_cow',
    buildingId: 'feed_mill',
    name: 'Коровий корм x3',
    outputItemId: 'cow_feed',
    outputCount: 3,
    craftTimeSeconds: 10,
    ingredients: [
      { itemId: 'corn', count: 1 },
      { itemId: 'soybean', count: 2 },
    ],
    unlockLevel: 2,
    xpGain: 4,
  },
  feed_pig: {
    id: 'feed_pig',
    buildingId: 'feed_mill',
    name: 'Свиной корм x3',
    outputItemId: 'pig_feed',
    outputCount: 3,
    craftTimeSeconds: 20,
    ingredients: [
      { itemId: 'carrot', count: 2 },
      { itemId: 'soybean', count: 1 },
    ],
    unlockLevel: 6,
    xpGain: 6,
  },
  feed_sheep: {
    id: 'feed_sheep',
    buildingId: 'feed_mill',
    name: 'Овечий корм x3',
    outputItemId: 'sheep_feed',
    outputCount: 3,
    craftTimeSeconds: 30,
    ingredients: [
      { itemId: 'wheat', count: 3 },
      { itemId: 'soybean', count: 1 },
    ],
    unlockLevel: 10,
    xpGain: 8,
  },
  feed_goat: {
    id: 'feed_goat',
    buildingId: 'feed_mill',
    name: 'Козий корм x3',
    outputItemId: 'goat_feed',
    outputCount: 3,
    craftTimeSeconds: 40,
    ingredients: [
      { itemId: 'wheat', count: 2 },
      { itemId: 'corn', count: 2 },
      { itemId: 'carrot', count: 1 },
    ],
    unlockLevel: 16,
    xpGain: 10,
  },

  // === BAKERY ===
  bake_bread: {
    id: 'bake_bread',
    buildingId: 'bakery',
    name: 'Хлеб',
    outputItemId: 'bread',
    outputCount: 1,
    craftTimeSeconds: 15,
    ingredients: [{ itemId: 'wheat', count: 3 }],
    unlockLevel: 1,
    xpGain: 6,
  },
  bake_corn_bread: {
    id: 'bake_corn_bread',
    buildingId: 'bakery',
    name: 'Кукурузный хлеб',
    outputItemId: 'corn_bread',
    outputCount: 1,
    craftTimeSeconds: 30,
    ingredients: [
      { itemId: 'corn', count: 2 },
      { itemId: 'egg', count: 1 },
    ],
    unlockLevel: 3,
    xpGain: 12,
  },
  bake_cookie: {
    id: 'bake_cookie',
    buildingId: 'bakery',
    name: 'Печенье',
    outputItemId: 'cookie',
    outputCount: 1,
    craftTimeSeconds: 60,
    ingredients: [
      { itemId: 'wheat', count: 2 },
      { itemId: 'egg', count: 1 },
      { itemId: 'brown_sugar', count: 1 },
    ],
    unlockLevel: 5,
    xpGain: 16,
  },
  bake_muffin: {
    id: 'bake_muffin',
    buildingId: 'bakery',
    name: 'Маффин с малиной',
    outputItemId: 'muffin',
    outputCount: 1,
    craftTimeSeconds: 90,
    ingredients: [
      { itemId: 'wheat', count: 2 },
      { itemId: 'raspberry_fruit', count: 2 },
      { itemId: 'egg', count: 1 },
    ],
    unlockLevel: 9,
    xpGain: 22,
  },
  bake_pizza: {
    id: 'bake_pizza',
    buildingId: 'bakery',
    name: 'Пицца',
    outputItemId: 'pizza',
    outputCount: 1,
    craftTimeSeconds: 120,
    ingredients: [
      { itemId: 'wheat', count: 2 },
      { itemId: 'cheese', count: 1 },
      { itemId: 'tomato', count: 2 },
    ],
    unlockLevel: 12,
    xpGain: 45,
  },
  bake_spicy_pizza: {
    id: 'bake_spicy_pizza',
    buildingId: 'bakery',
    name: 'Острая пицца',
    outputItemId: 'spicy_pizza',
    outputCount: 1,
    craftTimeSeconds: 150,
    ingredients: [
      { itemId: 'wheat', count: 2 },
      { itemId: 'cheese', count: 1 },
      { itemId: 'bacon', count: 1 },
      { itemId: 'chili', count: 1 },
    ],
    unlockLevel: 14,
    xpGain: 55,
  },
  bake_bagel: {
    id: 'bake_bagel',
    buildingId: 'bakery',
    name: 'Бейгл',
    outputItemId: 'bagel',
    outputCount: 1,
    craftTimeSeconds: 80,
    ingredients: [
      { itemId: 'wheat', count: 3 },
      { itemId: 'butter', count: 1 },
    ],
    unlockLevel: 15,
    xpGain: 26,
  },

  // === DAIRY ===
  dairy_cream: {
    id: 'dairy_cream',
    buildingId: 'dairy',
    name: 'Сливки',
    outputItemId: 'cream',
    outputCount: 1,
    craftTimeSeconds: 20,
    ingredients: [{ itemId: 'milk', count: 1 }],
    unlockLevel: 2,
    xpGain: 12,
  },
  dairy_butter: {
    id: 'dairy_butter',
    buildingId: 'dairy',
    name: 'Сливочное масло',
    outputItemId: 'butter',
    outputCount: 1,
    craftTimeSeconds: 45,
    ingredients: [{ itemId: 'milk', count: 2 }],
    unlockLevel: 4,
    xpGain: 20,
  },
  dairy_cheese: {
    id: 'dairy_cheese',
    buildingId: 'dairy',
    name: 'Сыр',
    outputItemId: 'cheese',
    outputCount: 1,
    craftTimeSeconds: 70,
    ingredients: [{ itemId: 'milk', count: 3 }],
    unlockLevel: 6,
    xpGain: 28,
  },
  dairy_goat_cheese: {
    id: 'dairy_goat_cheese',
    buildingId: 'dairy',
    name: 'Козий сыр',
    outputItemId: 'goat_cheese',
    outputCount: 1,
    craftTimeSeconds: 90,
    ingredients: [{ itemId: 'goat_milk', count: 2 }],
    unlockLevel: 16,
    xpGain: 38,
  },
  dairy_yogurt: {
    id: 'dairy_yogurt',
    buildingId: 'dairy',
    name: 'Йогурт',
    outputItemId: 'yogurt',
    outputCount: 1,
    craftTimeSeconds: 80,
    ingredients: [
      { itemId: 'milk', count: 2 },
      { itemId: 'strawberry', count: 2 },
    ],
    unlockLevel: 18,
    xpGain: 32,
  },

  // === SUGAR MILL ===
  sugar_brown: {
    id: 'sugar_brown',
    buildingId: 'sugar_mill',
    name: 'Тростниковый сахар',
    outputItemId: 'brown_sugar',
    outputCount: 1,
    craftTimeSeconds: 20,
    ingredients: [{ itemId: 'sugarcane', count: 1 }],
    unlockLevel: 5,
    xpGain: 8,
  },
  sugar_white: {
    id: 'sugar_white',
    name: 'Белый сахар',
    buildingId: 'sugar_mill',
    outputItemId: 'white_sugar',
    outputCount: 1,
    craftTimeSeconds: 50,
    ingredients: [{ itemId: 'sugarcane', count: 2 }],
    unlockLevel: 7,
    xpGain: 12,
  },
  sugar_syrup: {
    id: 'sugar_syrup',
    name: 'Сахарный сироп',
    buildingId: 'sugar_mill',
    outputItemId: 'syrup',
    outputCount: 1,
    craftTimeSeconds: 90,
    ingredients: [{ itemId: 'sugarcane', count: 4 }],
    unlockLevel: 11,
    xpGain: 20,
  },

  // === GRILL ===
  grill_pancake: {
    id: 'grill_pancake',
    buildingId: 'grill',
    name: 'Блинчики с сиропом',
    outputItemId: 'pancake',
    outputCount: 1,
    craftTimeSeconds: 30,
    ingredients: [
      { itemId: 'egg', count: 1 },
      { itemId: 'brown_sugar', count: 1 },
    ],
    unlockLevel: 5,
    xpGain: 26,
  },
  grill_bacon_eggs: {
    id: 'grill_bacon_eggs',
    buildingId: 'grill',
    name: 'Яичница с беконом',
    outputItemId: 'bacon_eggs',
    outputCount: 1,
    craftTimeSeconds: 60,
    ingredients: [
      { itemId: 'egg', count: 2 },
      { itemId: 'bacon', count: 2 },
    ],
    unlockLevel: 7,
    xpGain: 35,
  },
  grill_roast_potato: {
    id: 'grill_roast_potato',
    buildingId: 'grill',
    name: 'Печёный картофель',
    outputItemId: 'roast_potato',
    outputCount: 1,
    craftTimeSeconds: 45,
    ingredients: [
      { itemId: 'potato', count: 2 },
      { itemId: 'butter', count: 1 },
    ],
    unlockLevel: 8,
    xpGain: 30,
  },
  grill_hamburger: {
    id: 'grill_hamburger',
    buildingId: 'grill',
    name: 'Бургер',
    outputItemId: 'hamburger',
    outputCount: 1,
    craftTimeSeconds: 80,
    ingredients: [
      { itemId: 'bread', count: 1 },
      { itemId: 'bacon', count: 1 },
      { itemId: 'lettuce', count: 1 },
    ],
    unlockLevel: 10,
    xpGain: 42,
  },
  grill_fish: {
    id: 'grill_fish',
    buildingId: 'grill',
    name: 'Рыба на гриле',
    outputItemId: 'grilled_fish',
    outputCount: 1,
    craftTimeSeconds: 90,
    ingredients: [
      { itemId: 'perch', count: 1 },
      { itemId: 'chili', count: 1 },
    ],
    unlockLevel: 13,
    xpGain: 50,
  },
  grill_veggies: {
    id: 'grill_veggies',
    buildingId: 'grill',
    name: 'Овощи гриль',
    outputItemId: 'grilled_veggies',
    outputCount: 1,
    craftTimeSeconds: 70,
    ingredients: [
      { itemId: 'tomato', count: 2 },
      { itemId: 'onion', count: 1 },
      { itemId: 'chili', count: 1 },
    ],
    unlockLevel: 15,
    xpGain: 36,
  },

  // === PIE OVEN ===
  pie_carrot: {
    id: 'pie_carrot',
    buildingId: 'pie_oven',
    name: 'Морковный пирог',
    outputItemId: 'carrot_pie',
    outputCount: 1,
    craftTimeSeconds: 45,
    ingredients: [
      { itemId: 'carrot', count: 3 },
      { itemId: 'wheat', count: 2 },
      { itemId: 'egg', count: 1 },
    ],
    unlockLevel: 6,
    xpGain: 22,
  },
  pie_pumpkin: {
    id: 'pie_pumpkin',
    buildingId: 'pie_oven',
    name: 'Тыквенный пирог',
    outputItemId: 'pumpkin_pie',
    outputCount: 1,
    craftTimeSeconds: 75,
    ingredients: [
      { itemId: 'pumpkin', count: 2 },
      { itemId: 'wheat', count: 2 },
      { itemId: 'egg', count: 1 },
    ],
    unlockLevel: 9,
    xpGain: 34,
  },
  pie_bacon: {
    id: 'pie_bacon',
    buildingId: 'pie_oven',
    name: 'Киш с беконом',
    outputItemId: 'bacon_pie',
    outputCount: 1,
    craftTimeSeconds: 100,
    ingredients: [
      { itemId: 'bacon', count: 2 },
      { itemId: 'wheat', count: 2 },
      { itemId: 'egg', count: 2 },
    ],
    unlockLevel: 11,
    xpGain: 44,
  },
  pie_apple: {
    id: 'pie_apple',
    buildingId: 'pie_oven',
    name: 'Яблочный пирог',
    outputItemId: 'apple_pie',
    outputCount: 1,
    craftTimeSeconds: 120,
    ingredients: [
      { itemId: 'apple_fruit', count: 2 },
      { itemId: 'wheat', count: 2 },
      { itemId: 'white_sugar', count: 1 },
    ],
    unlockLevel: 14,
    xpGain: 52,
  },
  pie_fish: {
    id: 'pie_fish',
    buildingId: 'pie_oven',
    name: 'Рыбный пирог',
    outputItemId: 'fish_pie',
    outputCount: 1,
    craftTimeSeconds: 140,
    ingredients: [
      { itemId: 'trout', count: 1 },
      { itemId: 'wheat', count: 2 },
      { itemId: 'egg', count: 1 },
    ],
    unlockLevel: 17,
    xpGain: 60,
  },

  // === JUICER ===
  juice_carrot: {
    id: 'juice_carrot',
    buildingId: 'juicer',
    name: 'Морковный сок',
    outputItemId: 'carrot_juice',
    outputCount: 1,
    craftTimeSeconds: 30,
    ingredients: [{ itemId: 'carrot', count: 3 }],
    unlockLevel: 7,
    xpGain: 14,
  },
  juice_apple: {
    id: 'juice_apple',
    buildingId: 'juicer',
    name: 'Яблочный сок',
    outputItemId: 'apple_juice',
    outputCount: 1,
    craftTimeSeconds: 60,
    ingredients: [{ itemId: 'apple_fruit', count: 2 }],
    unlockLevel: 9,
    xpGain: 25,
  },
  juice_tomato: {
    id: 'juice_tomato',
    buildingId: 'juicer',
    name: 'Томатный сок',
    outputItemId: 'tomato_juice',
    outputCount: 1,
    craftTimeSeconds: 70,
    ingredients: [{ itemId: 'tomato', count: 3 }],
    unlockLevel: 10,
    xpGain: 28,
  },
  juice_cherry: {
    id: 'juice_cherry',
    buildingId: 'juicer',
    name: 'Вишнёвый сок',
    outputItemId: 'cherry_juice',
    outputCount: 1,
    craftTimeSeconds: 80,
    ingredients: [{ itemId: 'cherry_fruit', count: 2 }],
    unlockLevel: 12,
    xpGain: 32,
  },
  juice_lemonade: {
    id: 'juice_lemonade',
    buildingId: 'juicer',
    name: 'Лимонад',
    outputItemId: 'lemonade',
    outputCount: 1,
    craftTimeSeconds: 90,
    ingredients: [
      { itemId: 'lemon_fruit', count: 2 },
      { itemId: 'white_sugar', count: 1 },
    ],
    unlockLevel: 13,
    xpGain: 38,
  },
  juice_orange: {
    id: 'juice_orange',
    buildingId: 'juicer',
    name: 'Апельсиновый фреш',
    outputItemId: 'orange_juice',
    outputCount: 1,
    craftTimeSeconds: 100,
    ingredients: [{ itemId: 'orange_fruit', count: 2 }],
    unlockLevel: 15,
    xpGain: 42,
  },
  juice_berry_smoothie: {
    id: 'juice_berry_smoothie',
    buildingId: 'juicer',
    name: 'Ягодный смузи',
    outputItemId: 'berry_smoothie',
    outputCount: 1,
    craftTimeSeconds: 110,
    ingredients: [
      { itemId: 'raspberry_fruit', count: 2 },
      { itemId: 'blackberry_fruit', count: 2 },
      { itemId: 'milk', count: 1 },
    ],
    unlockLevel: 17,
    xpGain: 50,
  },

  // === LOOM ===
  loom_cotton_fabric: {
    id: 'loom_cotton_fabric',
    buildingId: 'loom',
    name: 'Хлопковая ткань',
    outputItemId: 'cotton_fabric',
    outputCount: 1,
    craftTimeSeconds: 40,
    ingredients: [{ itemId: 'cotton', count: 3 }],
    unlockLevel: 10,
    xpGain: 20,
  },
  loom_wool_yarn: {
    id: 'loom_wool_yarn',
    buildingId: 'loom',
    name: 'Шерстяная пряжа',
    outputItemId: 'wool_yarn',
    outputCount: 1,
    craftTimeSeconds: 60,
    ingredients: [{ itemId: 'wool', count: 2 }],
    unlockLevel: 11,
    xpGain: 28,
  },

  // === SEWING SHOP ===
  sew_sweater: {
    id: 'sew_sweater',
    buildingId: 'sewing_shop',
    name: 'Шерстяной свитер',
    outputItemId: 'sweater',
    outputCount: 1,
    craftTimeSeconds: 100,
    ingredients: [{ itemId: 'wool_yarn', count: 2 }],
    unlockLevel: 12,
    xpGain: 62,
  },
  sew_cotton_shirt: {
    id: 'sew_cotton_shirt',
    buildingId: 'sewing_shop',
    name: 'Хлопковая рубашка',
    outputItemId: 'cotton_shirt',
    outputCount: 1,
    craftTimeSeconds: 80,
    ingredients: [{ itemId: 'cotton_fabric', count: 2 }],
    unlockLevel: 13,
    xpGain: 52,
  },
  sew_warm_beanie: {
    id: 'sew_warm_beanie',
    buildingId: 'sewing_shop',
    name: 'Тёплая шапка',
    outputItemId: 'warm_beanie',
    outputCount: 1,
    craftTimeSeconds: 60,
    ingredients: [{ itemId: 'wool_yarn', count: 1 }],
    unlockLevel: 14,
    xpGain: 40,
  },
  sew_dress: {
    id: 'sew_dress',
    buildingId: 'sewing_shop',
    name: 'Летнее платье',
    outputItemId: 'dress',
    outputCount: 1,
    craftTimeSeconds: 130,
    ingredients: [
      { itemId: 'cotton_fabric', count: 2 },
      { itemId: 'strawberry', count: 2 },
    ],
    unlockLevel: 16,
    xpGain: 78,
  },

  // === CONFECTIONERY ===
  sweet_caramel: {
    id: 'sweet_caramel',
    buildingId: 'confectionery',
    name: 'Карамель',
    outputItemId: 'caramel',
    outputCount: 1,
    craftTimeSeconds: 60,
    ingredients: [
      { itemId: 'brown_sugar', count: 1 },
      { itemId: 'butter', count: 1 },
    ],
    unlockLevel: 11,
    xpGain: 32,
  },
  sweet_lollipop: {
    id: 'sweet_lollipop',
    buildingId: 'confectionery',
    name: 'Леденец',
    outputItemId: 'lollipop',
    outputCount: 1,
    craftTimeSeconds: 70,
    ingredients: [
      { itemId: 'syrup', count: 1 },
      { itemId: 'cherry_fruit', count: 1 },
    ],
    unlockLevel: 13,
    xpGain: 38,
  },
  sweet_toffee: {
    id: 'sweet_toffee',
    buildingId: 'confectionery',
    name: 'Ирис',
    outputItemId: 'toffee',
    outputCount: 1,
    craftTimeSeconds: 85,
    ingredients: [
      { itemId: 'white_sugar', count: 1 },
      { itemId: 'cream', count: 1 },
    ],
    unlockLevel: 15,
    xpGain: 48,
  },
  sweet_chocolate: {
    id: 'sweet_chocolate',
    buildingId: 'confectionery',
    name: 'Плитка шоколада',
    outputItemId: 'chocolate_bar',
    outputCount: 1,
    craftTimeSeconds: 120,
    ingredients: [
      { itemId: 'cacao_fruit', count: 3 },
      { itemId: 'white_sugar', count: 1 },
      { itemId: 'milk', count: 1 },
    ],
    unlockLevel: 16,
    xpGain: 58,
  },
  sweet_cotton_candy: {
    id: 'sweet_cotton_candy',
    buildingId: 'confectionery',
    name: 'Сахарная вата',
    outputItemId: 'cotton_candy',
    outputCount: 1,
    craftTimeSeconds: 90,
    ingredients: [
      { itemId: 'white_sugar', count: 2 },
      { itemId: 'raspberry_fruit', count: 1 },
    ],
    unlockLevel: 17,
    xpGain: 42,
  },

  // === ICE CREAM MAKER ===
  ice_vanilla: {
    id: 'ice_vanilla',
    buildingId: 'ice_cream_maker',
    name: 'Ванильное мороженое',
    outputItemId: 'vanilla_icecream',
    outputCount: 1,
    craftTimeSeconds: 60,
    ingredients: [
      { itemId: 'cream', count: 1 },
      { itemId: 'white_sugar', count: 1 },
      { itemId: 'milk', count: 1 },
    ],
    unlockLevel: 12,
    xpGain: 36,
  },
  ice_cherry_popsicle: {
    id: 'ice_cherry_popsicle',
    buildingId: 'ice_cream_maker',
    name: 'Вишнёвый эскимо',
    outputItemId: 'cherry_popsicle',
    outputCount: 1,
    craftTimeSeconds: 70,
    ingredients: [
      { itemId: 'cherry_juice', count: 1 },
      { itemId: 'syrup', count: 1 },
    ],
    unlockLevel: 13,
    xpGain: 44,
  },
  ice_strawberry: {
    id: 'ice_strawberry',
    buildingId: 'ice_cream_maker',
    name: 'Клубничное мороженое',
    outputItemId: 'strawberry_icecream',
    outputCount: 1,
    craftTimeSeconds: 85,
    ingredients: [
      { itemId: 'cream', count: 1 },
      { itemId: 'white_sugar', count: 1 },
      { itemId: 'strawberry', count: 3 },
    ],
    unlockLevel: 15,
    xpGain: 52,
  },
  ice_chocolate_sundae: {
    id: 'ice_chocolate_sundae',
    buildingId: 'ice_cream_maker',
    name: 'Шоколадный сандай',
    outputItemId: 'chocolate_sundae',
    outputCount: 1,
    craftTimeSeconds: 120,
    ingredients: [
      { itemId: 'cream', count: 1 },
      { itemId: 'cacao_fruit', count: 2 },
      { itemId: 'white_sugar', count: 1 },
    ],
    unlockLevel: 17,
    xpGain: 70,
  },

  // === JAM MAKER ===
  jam_apple: {
    id: 'jam_apple',
    buildingId: 'jam_maker',
    name: 'Яблочное повидло',
    outputItemId: 'apple_jam',
    outputCount: 1,
    craftTimeSeconds: 100,
    ingredients: [
      { itemId: 'apple_fruit', count: 3 },
      { itemId: 'white_sugar', count: 1 },
    ],
    unlockLevel: 13,
    xpGain: 40,
  },
  jam_raspberry: {
    id: 'jam_raspberry',
    buildingId: 'jam_maker',
    name: 'Малиновое варенье',
    outputItemId: 'raspberry_jam',
    outputCount: 1,
    craftTimeSeconds: 110,
    ingredients: [
      { itemId: 'raspberry_fruit', count: 3 },
      { itemId: 'white_sugar', count: 1 },
    ],
    unlockLevel: 14,
    xpGain: 48,
  },
  jam_blackberry: {
    id: 'jam_blackberry',
    buildingId: 'jam_maker',
    name: 'Ежевичный джем',
    outputItemId: 'blackberry_jam',
    outputCount: 1,
    craftTimeSeconds: 120,
    ingredients: [
      { itemId: 'blackberry_fruit', count: 3 },
      { itemId: 'white_sugar', count: 1 },
    ],
    unlockLevel: 15,
    xpGain: 55,
  },
  jam_cherry: {
    id: 'jam_cherry',
    buildingId: 'jam_maker',
    name: 'Вишнёвый конфитюр',
    outputItemId: 'cherry_jam',
    outputCount: 1,
    craftTimeSeconds: 130,
    ingredients: [
      { itemId: 'cherry_fruit', count: 3 },
      { itemId: 'white_sugar', count: 1 },
    ],
    unlockLevel: 16,
    xpGain: 60,
  },
  jam_peach: {
    id: 'jam_peach',
    buildingId: 'jam_maker',
    name: 'Персиковый мармелад',
    outputItemId: 'peach_marmalade',
    outputCount: 1,
    craftTimeSeconds: 150,
    ingredients: [
      { itemId: 'peach_fruit', count: 3 },
      { itemId: 'white_sugar', count: 2 },
    ],
    unlockLevel: 19,
    xpGain: 68,
  },

  // === COFFEE SHOP ===
  coffee_espresso: {
    id: 'coffee_espresso',
    buildingId: 'coffee_shop',
    name: 'Эспрессо',
    outputItemId: 'espresso',
    outputCount: 1,
    craftTimeSeconds: 40,
    ingredients: [{ itemId: 'coffee_bean', count: 3 }],
    unlockLevel: 14,
    xpGain: 42,
  },
  coffee_cappuccino: {
    id: 'coffee_cappuccino',
    buildingId: 'coffee_shop',
    name: 'Капучино',
    outputItemId: 'cappuccino',
    outputCount: 1,
    craftTimeSeconds: 60,
    ingredients: [
      { itemId: 'coffee_bean', count: 2 },
      { itemId: 'milk', count: 1 },
      { itemId: 'white_sugar', count: 1 },
    ],
    unlockLevel: 15,
    xpGain: 56,
  },
  coffee_hot_chocolate: {
    id: 'coffee_hot_chocolate',
    buildingId: 'coffee_shop',
    name: 'Горячий шоколад',
    outputItemId: 'hot_chocolate',
    outputCount: 1,
    craftTimeSeconds: 80,
    ingredients: [
      { itemId: 'cacao_fruit', count: 2 },
      { itemId: 'cream', count: 1 },
      { itemId: 'white_sugar', count: 1 },
    ],
    unlockLevel: 16,
    xpGain: 72,
  },
  coffee_iced_latte: {
    id: 'coffee_iced_latte',
    buildingId: 'coffee_shop',
    name: 'Айс латте',
    outputItemId: 'iced_latte',
    outputCount: 1,
    craftTimeSeconds: 70,
    ingredients: [
      { itemId: 'coffee_bean', count: 2 },
      { itemId: 'milk', count: 2 },
      { itemId: 'syrup', count: 1 },
    ],
    unlockLevel: 17,
    xpGain: 65,
  },
  coffee_mocha: {
    id: 'coffee_mocha',
    buildingId: 'coffee_shop',
    name: 'Мокачино',
    outputItemId: 'mocha',
    outputCount: 1,
    craftTimeSeconds: 100,
    ingredients: [
      { itemId: 'coffee_bean', count: 2 },
      { itemId: 'cacao_fruit', count: 1 },
      { itemId: 'cream', count: 1 },
    ],
    unlockLevel: 18,
    xpGain: 80,
  },
};
